### ISSUE TITLE
Teleporting between Nether and Overworld

### ISSUE THREAD

**Issue by Polda03** [xJon/Hexxit-II#103]
**Basic details**
Im using java 64
I haven't added any mods
Crashing always when i teleport back to overworld
https://paste.ubuntu.com or https://pastebin.com/index.

![image](https://user-images.githubusercontent.com/97835277/149660900-1c7dd419-2050-4400-92f7-caff200aea5a.png)

**Comment by xJon** [comment]
Can you please include the crash log?

**Comment by xJon** [comment]
Closing this as it is most likely a duplicate of https://github.com/xJon/Hexxit-II/issues/97.
