### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by darkwolfofficial** [xJon/Hexxit-II#104]
Failed to download https://libraries.minecraft.net/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar 
What should I do?

**Comment by xJon** [comment]
Hi! For modpack download / launcher issues make sure to head over to Technic's `#tech-help` Discord channel and upload your log there: https://discord.gg/KJjbBFSma5
