### ISSUE TITLE
Terrible stuttering while in game

### ISSUE THREAD

**Issue by DeliriousCooks** [xJon/Hexxit-II#106]
Whenever i load into a world ( multiplayer or single player ) i stutter every second or so

ive tried lowering render distance, allocating between 6-12GBs of ram, chaning args, lowering chunk distance, etc

my specs are 
I9-9900k
RTX 3090
64GB of DDR4-3600 Ram

**Comment by xJon** [comment]
Hi! Try disabling Dynamic Lights by pressing `L`.

**Comment by vyrzdev** [comment]
This worked for me!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
