### ISSUE TITLE
Missing stone tool recipes for some Natura sticks

### ISSUE THREAD

**Issue by EliasWorthing** [xJon/Hexxit-II#107]
I noticed that there are no stone tool recipes for several of the special stick types added by natura don't have recipes for vanilla stone tools.

**Comment by xJon** [comment]
Hi, thank you for the report! This seems to be an incompatibility due to a feature from the Quark mod, but we will fix this using CraftTweaker scripts in the next update.

**Comment by xJon** [comment]
This is fixed in the latest version of the modpack (`1.3.1`)!
