### ISSUE TITLE
Fairy Lights don't render due to Entity Culling incompatibility

### ISSUE THREAD

**Issue by xJon** [xJon/Hexxit-II#11]
Duplicate of https://github.com/Meldexun/EntityCulling/issues/31.
Only workaround currently is to disable Entity Culling, but this will have negative impact on performance.

**Comment by CunninghamPatrick** [comment]
Instead of globally disabling Entity Culling, a slightly better workaround is to set `skipHiddenTileEntityRendering` to false. This disables entity culling on TileEntities only, instead of on all entities, hopefully with a lesser impact on performance.

**Comment by xJon** [comment]
> Instead of globally disabling Entity Culling, a slightly better workaround is to set `skipHiddenTileEntityRendering` to false in the mod config. This disables entity culling on TileEntities only, instead of on all entities, hopefully with a lesser impact on performance.

That is a good tip, thank you! What do you think about setting this as default for the next update? As Hexxit II doesn't have as many TileEntities as it does entities.

**Comment by xJon** [comment]
This is fixed in the latest update!
