### ISSUE TITLE
Major Hopper Lag

### ISSUE THREAD

**Issue by thejbone** [xJon/Hexxit-II#110]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: Yes, Mohist
- **Crash/latest log link (if applicable)**: https://spark.lucko.me/3MhHzHwHiq

I found that hoppers cause lag. I am not sure how to describe it other than that. I find them using LagAssist (spigot plugin) and immediately after deleted the lag no longer occurs.

I am not sure if this is related to 1.3.0, as this has yet to occur then. I hosted for months prior to 1.3.0 without any hopper lag issues. The TPS from this will drop from a good solid 20, to 0-8, when this occurs. I am quickly able to fix it by using worldedit to replace all hoppers in the area with air. 

I have disabled FoamFix's hopper fix, and the issue still occurs, as that was the only hopper modification I could find in the config folder.

**Comment by xJon** [comment]
Hi! Can you try to reproduce this in a server with no plugins or Mohist added?

**Comment by Jaari** [comment]
Please update your mohist version anyways, they've had issues with hopper tile entities not unloading correctly.

**Comment by thejbone** [comment]
I updated the Mohist and no I have not been able to reproduce this recently, although my player count has been extremely low due to the modpack causing high ping issues when in the overworld a lot of the time. #127

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
