### ISSUE TITLE
Backpack Mod

### ISSUE THREAD

**Issue by jokerdog11** [xJon/Hexxit-II#111]
The backpack mod is great when you have to cheat for it to work properly. whenever I make any version of it it wont show that it is craftable. I double checked the recipe and im doing it right. When I go into cheat mode I am able to put it in my inventory and use it properly. If you could fix this that would be awesome.

**Comment by xJon** [comment]
Hi! Can you please explain exactly the issue with steps to reproduce it?

**Comment by jokerdog11** [comment]
This best way I can explain it. I'm trying to make the big backpack. In order to do this, I need three things. I need the top part of the backpack and the middle and lower parts of the backpack. I have to create each individual part and then align them in the crafting table to make the big backpack. Once I align all three parts in the crafting table the Big backpack does not appear in the craftable box on the crafting table. If I go into cheat mode and select the big backpack it works.

**Comment by xJon** [comment]
Oh I see! Did you make sure to make all 3 components of the same tier?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
