### ISSUE TITLE
Error Updating

### ISSUE THREAD

**Issue by Thorid666** [xJon/Hexxit-II#112]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**:  not applicable
![Hexxit ll Error](https://user-images.githubusercontent.com/98175722/150561383-a0d15d9d-df9c-4928-bc90-0d79d490834a.PNG)

**Describe the issue**

Every 
![Hexxit ll Error](https://user-images.githubusercontent.com/98175722/150561531-db91529d-f310-405f-bf7e-decd2da927b2.PNG)
time I try and Update I get this error, attached snip of error msg.

Error downloading a file for the following pack: Hexxit ll

Failed to download https://mirror.technicpack.net/Technic/mods/z-hexxit2-configs/z-hexxit2-configs-1.3.1.zip

**Comment by Thorid666** [comment]
[B#709] javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
[B#709] 	at sun.security.ssl.Alert.createSSLException(Unknown Source)
[B#709] 	at sun.security.ssl.TransportContext.fatal(Unknown Source)
[B#709] 	at sun.security.ssl.TransportContext.fatal(Unknown Source)
[B#709] 	at sun.security.ssl.TransportContext.fatal(Unknown Source)
[B#709] 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
[B#709] 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
[B#709] 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
[B#709] 	at sun.security.ssl.SSLHandshake.consume(Unknown Source)
[B#709] 	at sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
[B#709] 	at sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
[B#709] 	at sun.security.ssl.TransportContext.dispatch(Unknown Source)
[B#709] 	at sun.security.ssl.SSLTransport.decode(Unknown Source)
[B#709] 	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
[B#709] 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
[B#709] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[B#709] 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[B#709] 	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
[B#709] 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
[B#709] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[B#709] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#709] 	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
[B#709] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
[B#709] 	at net.technicpack.launchercore.mirror.download.Download.run(Download.java:72)
[B#709] 	at net.technicpack.utilslib.Utils.downloadFile(Utils.java:252)
[B#709] 	at net.technicpack.launchercore.install.tasks.DownloadFileTask.runTask(DownloadFileTask.java:65)
[B#709] 	at net.technicpack.launchercore.install.tasks.TaskGroup.runTask(TaskGroup.java:85)
[B#709] 	at net.technicpack.launchercore.install.InstallTasksQueue.runAllTasks(InstallTasksQueue.java:49)
[B#709] 	at net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:42)
[B#709] 	at net.technicpack.launcher.launch.Installer$1.run(Installer.java:123)
[B#709] 	at java.lang.Thread.run(Unknown Source)
[B#709] Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
[B#709] 	at sun.security.validator.PKIXValidator.doValidate(Unknown Source)
[B#709] 	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
[B#709] 	at sun.security.validator.Validator.validate(Unknown Source)
[B#709] 	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
[B#709] 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
[B#709] 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[B#709] 	... 26 more
[B#709] Caused by: java.security.cert.CertPathValidatorException: validity check failed
[B#709] 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(Unknown Source)
[B#709] 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
[B#709] 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
[B#709] 	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
[B#709] 	at java.security.cert.CertPathValidator.validate(Unknown Source)
[B#709] 	... 32 more
[B#709] Caused by: java.security.cert.CertificateNotYetValidException: NotBefore: Fri Jan 21 02:36:56 PST 2022
[B#709] 	at sun.security.x509.CertificateValidity.valid(Unknown Source)
[B#709] 	at sun.security.x509.X509CertImpl.checkValidity(Unknown Source)
[B#709] 	at sun.security.provider.certpath.BasicChecker.verifyValidity(Unknown Source)
[B#709] 	at sun.security.provider.certpath.BasicChecker.check(Unknown Source)
[B#709] 	... 37 more
[B#709] Download of https://mirror.technicpack.net/Technic/mods/z-hexxit2-configs/z-hexxit2-configs-1.3.1.zip Failed!

**Comment by xJon** [comment]
Hi! For modpack download / launcher issues make sure to head over to Technic's `#tech-help` Discord channel and upload your log there: https://discord.gg/KJjbBFSma5

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
