### ISSUE TITLE
Minecarts broken.

### ISSUE THREAD

**Issue by BirdSekhet** [xJon/Hexxit-II#113]
**Minecarts are broken. Can't get in them, cant break them.**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes, just the aether
- **Crash/latest log link (if applicable)**:  not applicable

**Describe the issue**

Minecarts are broken. Cnt get in them, cant break them.

**Comment by xJon** [comment]
Hi, can you provide any details of how to reproduce this issue? I am unable to.

**Comment by BirdSekhet** [comment]
Hi, sorry I just saw this. Whenever I try to enter one, or break it, I'm
unable to. Put one on the minecart, leave the chunk, and come back.

**Comment by xJon** [comment]
I tried to place one, leave the chunk and come back but I am still able to enter or break it. Does it happen to you on a server? Do you have any other reproduction steps?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
