### ISSUE TITLE
Continuous Falling through map after first death!

### ISSUE THREAD

**Issue by TeamFearlessFB** [xJon/Hexxit-II#116]
Help!
Me and my friends are new to the Hexxit II Sever! Upon joining my friend had died and is now stuck in a non-stop fall through the map! Any way to fix this or any tips to help him out? We have tried to TP him or even using the "/kill" command and nothing helps!

**Comment by xJon** [comment]
Hi! Did other players had no issues joining and playing on the server?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
