### ISSUE TITLE
OpenBlocks - Skyblock incompatibility with Lumen mod

### ISSUE THREAD

**Issue by BulletPR00FXX** [xJon/Hexxit-II#117]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**
A clear description of what the issue is.

When placing in inverted skyblock item from open blocks, instead of the single block looking like sky, the entire area looks like sky, even below you.  probably a mod issue, not a pack issue, but wanted to report it.

**Comment by xJon** [comment]
Seems like https://github.com/OpenMods/OpenBlocks/issues/763, although in this case it'd be a mod incompatibility.
I tested this thoroughly, and I found that this is an incompatibility with Lumen. Unfortunately neither Open Blocks nor Lumen are in active development so this might not get fixed, although both are open source if someone else wants to help.

**Comment by Cyyyy98** [comment]
What if I just got rid of Lumen or would that be a bad idea

**Comment by xJon** [comment]
@Cyyyy98 You can, but keep in mind that would mean your client would not be compatible with most Hexxit II servers.

**Comment by xJon** [comment]
Unless a developer fixes this issue on either of the conflicting mods' ends, there's nothing else I can do. Thanks for the report nevertheless!
