### ISSUE TITLE
No Heart Piece Drops shown in JEI

### ISSUE THREAD

**Issue by Salamyyy** [xJon/Hexxit-II#118]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**I wanted to check which mobs I exactly needed to kill to get myself some heart pieces/containers and I noticed that all of the Mobdrop pages in JEI for all of the mobs other than vanilla mobs have disappeared. But that's not all. In earlier versions it has shown me, that Ender dragons and Withers also dropped heart containers. That information disappeared as well. Did something change or is this a bug?

Thanks for the help in advance.

Salamyyy**

**Comment by xJon** [comment]
Hi!
That's true, this feature has been removed for now as it caused other issues.
For your reference, you can get heart pieces from mobs with over 21 health points (4%), and heart containers from boss mobs (25%).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
