### ISSUE TITLE
Inventory rollback

### ISSUE THREAD

**Issue by CehJota** [xJon/Hexxit-II#119]
I played for about 6 hours had a pretty severe setback where myu rogress was not rewittten during the back up. Usually only happens after long periods of play where inventory is reset to a previous state.

**Comment by xJon** [comment]
Odd, seems similar to https://github.com/xJon/Hexxit-II/issues/91.
What do you mean by "during the back up"? Did you try rolling back to a backup?
Also, can you fetch the game log of that exact session?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info!
