### ISSUE TITLE
No sound?

### ISSUE THREAD

**Issue by CehJota** [xJon/Hexxit-II#120]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes 
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**:  not applicable
I have been playing for a while and in addition to having my inventory rolled back none of the world, whether new or old have any sound. Like no mob sounds or block interaction sounds at all as though it was mute. The last thing to try is to unistall and reinstall, any other potential solutions? thanks

CehJota

**Comment by xJon** [comment]
Do you have any steps for reproducing this issue? Does it only happen in the one world?
Any additional information would be helpful.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
