### ISSUE TITLE
crash on generating world

### ISSUE THREAD

**Issue by yardak** [xJon/Hexxit-II#122]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: report:https://s2.dosya.tc/server16/7hlyiy/crash-2022-02-06_14.22.04-client.txt.html    https://s2.dosya.tc/server16/v8mo79/latest.log.html

**Help needed**
when I try to create the world it gives an error and says shutting down internal server. I reinstalled 2 times

**Comment by xJon** [comment]
Hi! Can you please share your crash report using https://pastebin.com/? Thanks!

**Comment by yardak** [comment]
https://pastebin.com/6sxgRms1

**Comment by xJon** [comment]
This crash usually occurs when not using a legitimate Minecraft account / launcher. If you are, just try to log out and back in the launcher :)
