### ISSUE TITLE
Can't play, world/Minecraft crashes

### ISSUE THREAD

**Issue by Allie1412** [xJon/Hexxit-II#123]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: crash-2022.02-12_09.33.27-client.txt

Hello, I wanted to play Minecraft again. So I downloaded Hexxit II and everything went perfectly. However, now when I try to create a new world, the world loads and then crashes with the message 'A problem occurred and it crashed. The following modifications have been identified as possible causes: Unknown.´

Can someone help me? I have already uninstalled and reinstalled Hexxit II, but the error does not go away.

**Comment by Jaari** [comment]
Please provide a screenshot of the launcher you are using.

**Comment by Allie1412** [comment]
> Please provide a screenshot of the launcher you are using.

I can't upload anything. But it´s the Windows Version of https://mc-launcher.com/launcher/technic.html

**Comment by Jaari** [comment]
> > Please provide a screenshot of the launcher you are using.
> 
> I can't upload anything. But it´s the Windows Version of https://mc-launcher.com/launcher/technic.html

Cracked launchers are not supported. Please download the official technic launcher here: https://www.technicpack.net/download

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested
