### ISSUE TITLE
Hexxit II can't play multiplayer

### ISSUE THREAD

**Issue by nicvalentine7** [xJon/Hexxit-II#124]
**Basic details**
- **Are you using Java 8, 64-bit?**: no / yes
- **Did you add any additional mods**: yes (detail) / no
- **Crash/latest log link (if applicable)**: link to log / not applicable

When trying to play my server on hexxit 2, I get an error in the top left part of my screen that says Online: (Red X)
Anyone know how to fix this?

**Help needed**

A clear description of what help is needed.

**Comment by CZG-408** [comment]
@nicvalentine7 are you anasianman#9227 on discord?

**Comment by nicvalentine7** [comment]
> @nicvalentine7 are you anasianman#9227 on discord?

Yep someone already helped me solve this

**Comment by CZG-408** [comment]
That was me, wanted to confirm. Jon, this can be marked as closes, I assisted them in #tech-help

**Comment by nicvalentine7** [comment]
> 

Awesome, thanks for the help.
