### ISSUE TITLE
(Suggestion/Mod Request) Replace ReAuth mod with OAuth mod

### ISSUE THREAD

**Issue by CZG-408** [xJon/Hexxit-II#125]
Hey Jon,

Hexxit 2 currently uses the ReAuth mod which is handy for when your login gets invalidated inside the game but only if you have mojang accounts which soon will disappear. Can it be replaced [OAuth Mod](https://www.curseforge.com/minecraft/mc-mods/OAuth) since that supports Microsoft accounts which will soon become the only type of account. It should also help prevent confusion regarding the X it shows when using Microsoft accounts.

**Comment by xJon** [comment]
That's a really good suggestion, and I'll make sure to do that in the next modpack update. Thank you!

**Comment by xJon** [comment]
Closing as this was done already :)
