### ISSUE TITLE
Knapsack doesn't work

### ISSUE THREAD

**Issue by TFC-343** [xJon/Hexxit-II#128]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: not applicable

Knapsack doesn't work

The _Traveller's Knapsack_ from the _Construct's Armory_ mod does not work;
 after applying the knapsack to a chest plate, pressing 'H' does not show the knapsack inventory as it should.

**Comment by xJon** [comment]
Did you confirm the key binding in the Controls menu?
