### ISSUE TITLE
Can't Craft Redstone Reception Coil from the Thermal Mod Series

### ISSUE THREAD

**Issue by GefahrVonRechts** [xJon/Hexxit-II#131]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: yes (The other Mods From the Thermal Series, so i added T. Cultivation, T. Expansion,...; Ice and Fire; Malisis Doors; Galacticraft with the Galaxy Space and the More Planets addon, Mekanism, Refined Storage, )
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

The Redstone Reception Coil is not Craftable. So the whole thermal Series is not really usable. I tried to craft it without the other mods from the thermal series but still didnt work.

**Comment by xJon** [comment]
Hi, this is intentional as Hexxit is an adventure modpack. If you want, you can always change this over `\hexxit-ii\config\cofh\thermalfoundation\common.cfg` L#453.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested
