### ISSUE TITLE
I keep getting booted from my session

### ISSUE THREAD

**Issue by BlairTheCat1** [xJon/Hexxit-II#132]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

every now and again the I will get booted from the game back to the menu. It will, out of nowhere without warning, say "shutting down internal server" without crashing. it's really irritating to not be able to play one session without this happening
 this is as specific as it gets and it's the only thig happening (BTW I have 9 GB allocated to the technic launcher). If there is a way to fix this please do so soon, thank you.

**Comment by xJon** [comment]
Hi! Can you please post your latest game log?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested
