### ISSUE TITLE
Cant load into a world

### ISSUE THREAD

**Issue by MrGlitchpop** [xJon/Hexxit-II#133]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: link to log 
crash-2022-04-08_01.15.41-client.txt

**Describe the issue**

Whenever i try to load into a world my game says "loading world" it then says shutting down internal server and shows me a screen saying "minecraft ran into a problem"
"the following mods have been identified as a cause" "unknown"

**Comment by xJon** [comment]
Hi! Can you please post your crash log using a paste-tool, such as https://pastebin.com?
