### ISSUE TITLE
Can't play single player 

### ISSUE THREAD

**Issue by nikoloa** [xJon/Hexxit-II#134]
**Basic details**  When I create a new world in single player it loads and it says "loading world" and after that "shutting down internal server..". 
"Minecraft crashed
Minecraft ran into a problem and crashed. The following mod(s) have been indentified as potential causes: unknown
And also the "Click the "link button"" does not work. 
- **Are you using Java 8, 64-bit?**: no / yes
- **Did you add any additional mods**: yes (detail) / no
- **Crash/latest log link (if applicable)**: link to log 
- crash-2022-04-08_14.14.32-client.txt

**Describe the issue**

A clear description of what the issue is.
I don't know what the issue with the single player is but the serfers that I play on work just fine, I go in , I go out, but the single player won't load. Help

**Comment by xJon** [comment]
Hi! Can you please post your crash log using a paste-tool, such as https://pastebin.com/?

**Comment by nikoloa** [comment]
https://pastebin.com/GbLmkbFv

**Comment by xJon** [comment]
You need to make sure you use a legitimate Minecraft account with the original Technic launcher.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested
