### ISSUE TITLE
Can't create world

### ISSUE THREAD

**Issue by radicno** [xJon/Hexxit-II#135]
- I am using Java 8, 64-bit
- I did not tamper with the game or mods 
- Crash report: [https://paste.ubuntu.com/p/GN6yjHWnCv/](https://paste.ubuntu.com/p/GN6yjHWnCv/)

Fresh launch of the game right after installing, have tried reinstalling a few times.

**Comment by radicno** [comment]
resolved: i pirated lol

**Comment by xJon** [comment]
Hah, did you resolve it by more pirating or purchasing the game?
