### ISSUE TITLE
Spongeforge Compat

### ISSUE THREAD

**Issue by ZiphonOfficial** [xJon/Hexxit-II#138]
Every time I try to use SpongeForge the server immediately crashes after indexing available mods. I am only using the versions SpongeForge has marked as stable and are specified for forge 2860 (the same version the modpack uses). Is there a version of SpongeForge that is known to be working?

Here are the PasteBin's incase anyone wanted to take a look at the errors.:
Crash Report: https://pastebin.com/THE6nD22
Debug-less Log: https://pastebin.com/kX4hBUQi
Debug Log: https://pastebin.com/f54BwbrB

**Comment by xJon** [comment]
I am not very experienced with SpongeForge, but I know some people use it with the modpack successfully.
Did you try to use SpongeForge on your system with other 1.12.2 modpacks and it worked fine? Also, the version you're using seems to be slightly outdated. Perhaps updating would help.
Let me know how it goes!

**Comment by ZiphonOfficial** [comment]
By outdated do you mean the version of SpongeForge or HexxitII? I have been running 3.1.2 for H2, and for SF I have used every recommended version of SF that was built for forge 2860 and all of them encountered the same issue. I did happen to narrow down what mod was conflicting with SF by the way. The streams mod and it's dependency fareek (I think its fareek, sorry if I butchered it) were causing SF's world saving methods to bug out because both SF and Streams were trying to take override methods for world generation and saving. I'm not very good at coding yet, but that's what I gathered when looking through the errors and doing some research online.

Removing those two mods fixed the issue, but now the beautiful rivers that your pack is supposed to have won't be seen by my friends. Which is a shame because Hexxit and Hexxit2 are beautiful packs. <3

**Comment by xJon** [comment]
You could try to reach out over Discord to some of the Hexxit II server owners who use SpongeForge, they might be able to help with this :)

**Comment by zediious** [comment]
Remove Streams from your server, unfortunately the problem somehow persists due to other mods in the modpack, despite the version used supposedly being fixed in the version used [https://docs.spongepowered.org/stable/en/server/spongineer/incompatible.html#farseek](https://docs.spongepowered.org/stable/en/server/spongineer/incompatible.html#farseek)

The file name for the current latest version is `Streams-1.12-0.4.9.jar`

The client can keep the mod jar, only the server needs to remove it.

This obviously has the side effect of removing the cool rivers. I am not sure what is causing this to happen.

**Comment by funAlways** [comment]
A bit late, I tried using spongeforge and another solution is to downgrade Streams to 0.4.8 (farseek is fine). This is pinned in SF's discord regarding MC Eternal. Though if you do this, then default hexxit 2 installs will have incompatibility with the server.

**Comment by xJon** [comment]
Closed due to inactivity. If Streams could ever get patched to resolve this issue I'd try to include that in a future modpack update.
Will reopen if requested!
