### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by JonasV73** [xJon/Hexxit-II#139]
hey i a quastion between a Hexxit II servers, 
it's about our Hexxit 2 server crashing from the moment when more than 2 people join, and the problem is that it doesn't happen with a Aternos servers... Here are our server specs -> i9 - 9900K 128GB DDR4 ECC RAM [2666Mhz] 2x 500GB NVMe hard disk storage 1 Gbit/s upload and download Location Germany

**Comment by xJon** [comment]
Hi, can you post your crash log using https://pastebin.com?

**Comment by JonasV73** [comment]
the server is not crashing, From 2 players and more, the server gets a timeout of over 100 seconds and hangs in an infinity loop
If you lower the max_tick_time it crashes out because of a timeout

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info :)
