### ISSUE TITLE
Server crashes when I log on 

### ISSUE THREAD

**Issue by jamcb19** [xJon/Hexxit-II#140]
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Help needed**

Hello. I am playing on a hexxit ii server. So I was building and I placed a framed slab down and the world crash. I haven't been able to log back onto the server. When it crashes it says it may have been cause by some of the mods.

**Comment by xJon** [comment]
Hi! Can you please post your crash log using https://pastebin.com?

**Comment by jamcb19** [comment]
That is another thing. When I try to get the link through clicking the "Get Link" button it says [Failed]

**Comment by xJon** [comment]
You can find the crash log in the modpack or server directory :)

**Comment by jamcb19** [comment]
Sorry I was having trouble with paste bin. When I tried to create the paste it gave me an error message. I was able to get a link from my server log though.  

https://mclo.gs/TNk7uF0

**Comment by xJon** [comment]
Seems to be an issue with the client and not with the server. Can you upload the client log?
