### ISSUE TITLE
Why am I not able to make rice paddies?

### ISSUE THREAD

**Issue by IroAoYaMaDa** [xJon/Hexxit-II#142]
**Basic details**
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: Yes (only OptiFine)
- **Crash/latest log link (if applicable)**: Not applicable

**Help needed**

I'm trying to build a farm for my Let's Play series, but I have the issue with one plant that just grows naturally or there's a mod conflict or features missing from this specific mod version: Rice. I did watch few tutorials and it says that I need rice paddies that can be made by right clicking a farmland with a shovel, but in Hexxit II, Minecraft 1.12.2 it doesn't seem to work at all, it doesn't turn into a paddy. It doesn't seem to require ropes like other Growthcraft plants do, like grapes and hops. So I'm here asking: Am I doing something wrong? Is there a mod conflict or is the mod bugged? Or could this potentially be that Growthcraft Rice in 1.12.2 is in Beta according to Growthcraft Wiki.

**Comment by xJon** [comment]
Hi! The relevant (updated) Growthcraft wiki can be found over: https://github.com/GrowthcraftCE/Growthcraft-1.12/wiki.
Instead of right clicking with a shovel, you need to use a Cultivator :)
