### ISSUE TITLE
I keep getting the same crash over and over again

### ISSUE THREAD

**Issue by desturr** [xJon/Hexxit-II#143]
I was playing in my world for 1 months. But now i cant login whenever i try to relog the world. It keeps giving me the same crash report and i dont understand the issue.
Im using java 64bit
I didnt add any additional mod

**CRASH REPORT LINK**

https://paste.ubuntu.com/p/NsNHkZdVRG/

I want to login to the world i used to play help pls :(

**Comment by xJon** [comment]
This crash usually occurs when not using a legitimate Minecraft account / launcher. If you are, just try to log out and back in the launcher :)
