### ISSUE TITLE
no giant miners in cloud cottage? 

### ISSUE THREAD

**Issue by nici68** [xJon/Hexxit-II#145]
henlo, i finally made it to cloud cottage and there is no miner and now i am stuck cause i cant get that giant word, :( my difficulty is normal and  I tried finding him but no success :(

**Comment by xJon** [comment]
That's odd! I haven't heard of such issue before. Unfortunately the Twilight Forest is no longer in active development so there's not much we can do about it. I'd suggest to "cheat" your way into finding another one.

**Comment by nici68** [comment]
Hello, I am not allowed to cheat in my world but I figured it out 😅 I
didn’t plant those colorful beans instead of this I build my way up there
with blocks so those giants spawns only when you get there by planting 😊
and also I have a question about that last castle. You said that twilight
forest is no longer in active development so there will be no final boss?
🥺 Thank you very much for answer, have a lovely day.

Dňa pi 6. 5. 2022 o 8:10 Jon ***@***.***> napísala(a):

**Comment by xJon** [comment]
@nici68 I'm glad you figured it out! About the final boss, unfortunately there is no real final boss at the moment, but the mod is open source and anyone could implement it in the future :)
