### ISSUE TITLE
oAuth issues

### ISSUE THREAD

**Issue by ApTR4t** [xJon/Hexxit-II#146]
hey getting an error on OAUTH.

![image](https://user-images.githubusercontent.com/85871550/166610995-cd2d1159-08e5-400e-b163-7cd5b7ada641.png)

**Comment by xJon** [comment]
This might've been addressed in the [latest version of the mod](https://www.curseforge.com/minecraft/mc-mods/oauth/files/3739783). You can attempt to manually update it and try again :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
