### ISSUE TITLE
cant use heal staff on a server

### ISSUE THREAD

**Issue by ELDeKay** [xJon/Hexxit-II#147]
**Basic details**
- **Are you using Java 8, 64-bit?  yes
- **Did you add any additional mods?  no

**Help needed**

A clear description of what help is needed.
So basically i cant use the heal staff as intented on a Hexxit II server. It is just a stick, I can hit my friend with it but cant heal him XD

**Comment by xJon** [comment]
Which specific healing staff are you referring to?

**Comment by ELDeKay** [comment]
its the "heal staff" Mod: elementary staffs, thanks in advance

**Comment by xJon** [comment]
Can you heal other entities with it?
