### ISSUE TITLE
Getting error when trying to install the modpack.

### ISSUE THREAD

**Issue by snkxD** [xJon/Hexxit-II#148]
**Basic details**
- **Are you using Java 8, 64-bit?**: no / yes yes
- **Did you add any additional mods**: yes (detail) / no no
- **Crash/latest log link (if applicable)**: link to log / not applicable not applicable

**Help needed**
![Error](https://user-images.githubusercontent.com/105635559/168557662-1cddbe07-cd88-48e1-9676-aad85fc7729c.PNG)

A clear description of what help is needed.

**Comment by xJon** [comment]
Hi! For modpack download / launcher issues make sure to head over to Technic's `#tech-help` Discord channel and upload your log there: https://discord.gg/KJjbBFSma5

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
