### ISSUE TITLE
Server Crash on Wordgen

### ISSUE THREAD

**Issue by smallerYeet** [xJon/Hexxit-II#149]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: yes (Addidtional-Compression, cc-Tweaked, additional lanturns, ftb ultimine, ironfurnaces, chunkloaders, Simplestorage Network.
- **Crash/latest log link (if applicable)**: https://pastebin.com/eAtasNFP)

Crashes when starting the server. The server can boot, but can't load the word, it seems. Backups didn't help. This happened after I tried altering the config files. But after reverting every config to original and loading two backups, the error persists.

**Comment by smallerYeet** [comment]
Found out that Farseek API is the issue. Removing the API and the mod "Streams" made me able to start the server. But how can I fix this with the mod installed?

**Comment by xJon** [comment]
Are you using SpongeForge with your server?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
