### ISSUE TITLE
do Pocket Dimesion generated portals regenerate?

### ISSUE THREAD

**Issue by sistosilvio** [xJon/Hexxit-II#150]
I found a portal which looks like a shiny mirror between some chiseled stone
I teleported into it and looked around for a bit then came back to the overworld.
After I came back the portal seems to be deactivated, thought it still has some particles coming out of it.

Will it ever regenerate back into an actual portal?
It does seem to be slowly morphing in some way. Very misterious...

Finally just wanna say I love the modpack.  It definitely is an adventure RPG modpack! it did not disapoint.  great job.

**Comment by xJon** [comment]
You probably encountered a Dimensional Doors portal! You can read more about the mod over [here](https://www.curseforge.com/minecraft/mc-mods/dimensionaldoors) and over Youtube.

And thank you so much for the positive feedback, it means a lot :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested :)
