### ISSUE TITLE
Dimensional Doors pocket dimension xp issue

### ISSUE THREAD

**Issue by KynLeg** [xJon/Hexxit-II#151]
After entering the personal pocket dimension you you lose all the xp gained sadly 
for this to happen you need just to enter the quarz door and there you go all xp is gone ..

**Comment by xJon** [comment]
This is most a glitch which will be fixed in the next update with the addition of [Fix Experience Bug](https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug/files/3372374) :)

**Comment by KynLeg** [comment]
Thank you dude <3

**Comment by xJon** [comment]
This should be resolved now :)
