### ISSUE TITLE
Enchantments Acting Finicky

### ISSUE THREAD

**Issue by KosherKingOfIsrael** [xJon/Hexxit-II#155]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

When using the Advanced Enchantment Table to enchant certain items such as the Hexxit Gear and staffs, the enchantment will apply and xp will be subtracted; however, the enchantment will be lost and xp will be refunded at any point afterwards when the player transfers the item to their inventory, or interacts with the item.
The refund and disenchantment happens seemingly at random, sometimes it is immediate, othertimes it happens later on, and if we get really lucky it doesn't happen at all.

**Comment by xJon** [comment]
Strange, can you reproduce this issue on other worlds as well?

**Comment by KosherKingOfIsrael** [comment]
> Strange, can you reproduce this issue on other worlds as well?

trying to right now, but enchantments seem to be working fine in Single Player. It might be exclusive to servers, but I can't really test that right now  without erasing my progress.

**Comment by xJon** [comment]
We'll keep an eye on this issue; I am planning a major new update soon for Hexxit II which should have a positive affect on some glitches.

**Comment by anOrcaDork** [comment]
I went to sleep in a bed for a new day to see if the time of day was effecting the glitch and it seems to fix the problem if you're enchanting at night time. (I have the Treasure bonus)

**Comment by xJon** [comment]
Unfortunately I am unable to reproduce this issue on a server as well. Let's test this on the upcoming version to see whether it's resolved or not.

**Comment by xJon** [comment]
Can you test whether this issue is still present with the latest version of the modpack? (`1.4.0`)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info!
