### ISSUE TITLE
I have bug while i am downloading the mod pack hexxit II

### ISSUE THREAD

**Issue by tomek14a14** [xJon/Hexxit-II#157]
download error for Hexxit II package
Failed to download https: //libaries.minecraft/.net/org/apache/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
consult the author of the package

**Comment by xJon** [comment]
Hi! For modpack download / launcher issues make sure to head over to Technic's `#tech-help` Discord channel and upload your log there: https://discord.gg/KJjbBFSma5

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
