### ISSUE TITLE
minecraft crashes when I connect to world

### ISSUE THREAD

**Issue by FlowdVN** [xJon/Hexxit-II#158]
![Hexxit II 6_8_2022 15_04_19](https://user-images.githubusercontent.com/107105275/172567183-6f496390-50e7-4200-b55b-d75b12b0a1e8.png)

**Comment by xJon** [comment]
Please post your crash log using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info :)
