### ISSUE TITLE
It crashes when I try to create or join a world

### ISSUE THREAD

**Issue by LeoBonhart1** [xJon/Hexxit-II#160]
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link **: https://pastebin.ubuntu.com/p/NvyJf48Mgh/

I just downloaded the modpack and whenever trying to create or join a world getting this crash

![crs](https://user-images.githubusercontent.com/104325150/175036697-b605e393-e450-46bd-ab08-dfb1462a937d.png)

**Comment by xJon** [comment]
This crash usually occurs when not using a legitimate Minecraft account / launcher. If you are, just try to log out and back in the launcher :)

**Comment by xJon** [comment]
Closed due to inactivity :)
