### ISSUE TITLE
Crash while loading a world

### ISSUE THREAD

**Issue by AgmonBlynkos** [xJon/Hexxit-II#161]
- Are you using Java 8, 64-bit?: yes
- Did you add any additional mods: no
- Crash/latest log link (if applicable): https://pastebin.ubuntu.com/p/6BwKfVRWwD/

I just installed this modpack today but it keeps crashing whenever I try to load a world, tried logging out and in the launcher again but it didn't work. I use a cracked version of mc and of the launcher

![Screenshot 2022-06-28 131817](https://user-images.githubusercontent.com/108335762/176156238-9d473830-7016-4698-b61d-79b26e5d6e78.png)

**Comment by xJon** [comment]
This crash usually occurs when not using a legitimate Minecraft account / launcher. If you are, just try to log out and back in the launcher :)

**Comment by xJon** [comment]
Closed due to inactivity :)
