### ISSUE TITLE
Achievements Resetting on Multiplayer Server

### ISSUE THREAD

**Issue by CainInstinct** [xJon/Hexxit-II#164]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes (mr crayfish's furniture mod and pam's harvestcraft. Achievements bug was present before they were added)
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**

On my multiplayer hexxit II server, out of the 3 active players I am the only one who experiences this issue. My achievements randomly reset, but only some of them and always without warning. This makes it very difficult in the case of things like the twilight forest bosses, where progression achievements are active and require me to have completed certain achievements in order to access certain areas or bosses. Neither of the other 2 players on the server experience this issue and their achievements have not reset at any point during the 2 months we have played on the server. The achievements that reset don't seem to follow any apparent pattern for the type that resets (ex: achievements from defeating bosses and achievements for equipping diamond armor resetting).

**Comment by xJon** [comment]
Hey, really sorry to hear about this issue!
You could try to backup and possibly revert your player's stats file in case this happens again.
You can find it in the server's world folder -> `stats` -> <your player UUID>.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
