### ISSUE TITLE
Hexxit II keeps crashing

### ISSUE THREAD

**Issue by SlimThiqqLizard** [xJon/Hexxit-II#165]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://pastebin.com/YnQs48CW

**Help needed**

I have been playing on this world for a few days now but for some reason whenever I went to join the world today, it would crash at the loading screen and show this:
![Hexxit crash](https://user-images.githubusercontent.com/109187735/178626719-c6d7ebfd-4c7d-4389-8533-90410e6629e9.png)

**Comment by xJon** [comment]
Seems like the save got corrupted, can you load one of the backups?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
