### ISSUE TITLE
could not create the java virtual machinge bug 

### ISSUE THREAD

**Issue by antifluffi** [xJon/Hexxit-II#166]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**

could not create the java virtual machine bug. Launcher works fine on vanilla minecraft but when I try to start the Technic Launcher Hexxit II it crashs instantly with this failure. 16 GB RAM gave the Game room for round about 5 in the Task Manager it says everythings fine. uninstalled and installed, nothing works. I have seriously no Idea... 
![zEHbQgq](https://user-images.githubusercontent.com/109491194/179432964-82c02615-2b3c-410c-808c-3dc9edbb8237.png)

Best Regards
fluffi

**Comment by xJon** [comment]
Hi! Can you launch other modpacks from the Technic Launcher?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
