### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by LucassLJ** [xJon/Hexxit-II#167]
Hi, I just installed Hexxit 2 and I can't start a new world because of this crash

![image](https://user-images.githubusercontent.com/96756294/180259829-ef1259d2-1f92-4b33-8e2d-d0e027fdc843.png)

**Comment by xJon** [comment]
Please include your crash report using https://pastebin.com

**Comment by LucassLJ** [comment]
I don't know how, i am clicking on '' get link '' but it's not working

![image](https://user-images.githubusercontent.com/96756294/180619441-ae80acd2-1467-4a82-b4c1-0edd430f76d0.png)

**Comment by xJon** [comment]
You can find it in the modpack's installation folder under `crash-reports`.

**Comment by LucassLJ** [comment]
[crash-2022-07-23_19.05.29-client.txt](https://github.com/xJon/Hexxit-II/files/9174739/crash-2022-07-23_19.05.29-client.txt)

**Comment by xJon** [comment]
This crash usually occurs when not using a legitimate Minecraft account / launcher. If you are, just try to log out and back in the launcher :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
