### ISSUE TITLE
hello i am playing minecarft hexxit 2 and there is no minimap, none of the keys open the minimap what should i do? is this a bug?

### ISSUE THREAD

**Issue by Eftron24** [xJon/Hexxit-II#168]
**Basic details**
- **Are you using Java 8, 64-bit?**: no / yes
- **Did you add any additional mods**: yes (detail) / no
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Describe the issue**

A clear description of what the issue is.

**Comment by xJon** [comment]
Hi, can you try to reset your key bindings to default and then press `M`?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
