### ISSUE TITLE
Longshot server bug

### ISSUE THREAD

**Issue by AmayaGSGW2** [xJon/Hexxit-II#169]
Hello there,
When player shoot the longshot thru portal, it drop the entire server. Inspect the log I attached here.
Version 1.4.0
Best Regards
[2022-07-28-4.log.gz](https://github.com/xJon/Hexxit-II/files/9213124/2022-07-28-4.log.gz)
.

**Comment by xJon** [comment]
Can you post the log using a paste tool? https://mclo.gs/

**Comment by AmayaGSGW2** [comment]
https://mclo.gs/OZg8QqO

**Comment by AmayaGSGW2** [comment]
[2022-07-28-4.log](https://github.com/xJon/Hexxit-II/files/9214556/2022-07-28-4.log)

**Comment by xJon** [comment]
Thank you for the report! Will forward this issue to the mod author to get it resolved.

**Comment by xJon** [comment]
Should be fixed in `1.4.2`!
