### ISSUE TITLE
Can't play, crashes every time

### ISSUE THREAD

**Issue by WormWalkerr** [xJon/Hexxit-II#170]
I can create a new world but can't join any of them. I always get a crash. I don't have a legitimate minecraft account so, I also tried to log out and back in to the launcher and then open the game again but that also didn't work.
Here's one of my crash logs,
https://mclo.gs/bni11yA

**Comment by WormWalkerr** [comment]
[crash-2022-07-29_04.00.05-client.txt](https://github.com/xJon/Hexxit-II/files/9215179/crash-2022-07-29_04.00.05-client.txt)
[crash-2022-07-29_04.01.18-client.txt](https://github.com/xJon/Hexxit-II/files/9215180/crash-2022-07-29_04.01.18-client.txt)
[crash-2022-07-29_04.02.33-client.txt](https://github.com/xJon/Hexxit-II/files/9215181/crash-2022-07-29_04.02.33-client.txt)
[crash-2022-07-29_04.07.33-client.txt](https://github.com/xJon/Hexxit-II/files/9215182/crash-2022-07-29_04.07.33-client.txt)
[crash-2022-07-29_03.40.52-client.txt](https://github.com/xJon/Hexxit-II/files/9215183/crash-2022-07-29_03.40.52-client.txt)
[crash-2022-07-29_03.41.12-client.txt](https://github.com/xJon/Hexxit-II/files/9215184/crash-2022-07-29_03.41.12-client.txt)
[crash-2022-07-29_03.44.38-client.txt](https://github.com/xJon/Hexxit-II/files/9215185/crash-2022-07-29_03.44.38-client.txt)

**Comment by xJon** [comment]
This crash usually occurs when not using a legitimate Minecraft account / launcher. If you are, just try to log out and back in the launcher :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
