### ISSUE TITLE
?

### ISSUE THREAD

**Issue by bojoc100** [xJon/Hexxit-II#171]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: link to log 

**Help needed**
[crash-2022-07-29_05.02.22-client.txt](https://github.com/xJon/Hexxit-II/files/9215476/crash-2022-07-29_05.02.22-client.txt)

**Comment by xJon** [comment]
This crash usually occurs when not using a legitimate Minecraft account / launcher. If you are, just try to log out and back in the launcher :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
