### ISSUE TITLE
I can´t open Construct´s armor accesories

### ISSUE THREAD

**Issue by Neikless** [xJon/Hexxit-II#172]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**

I was serching how to add travelers belt on my leggins, but i can´t open any of my Construct´s armor.
I tryed to change controls settings, but it didn´t help.
Please if you know how to fix it tell me.
Thank you.

**Comment by xJon** [comment]
[This tutorial video](https://youtu.be/wymqWrTczVk?t=484) might help you :)

**Comment by Neikless** [comment]
> [This tutorial video](https://youtu.be/wymqWrTczVk?t=484) might help you :)

Yes thank you very much, but for some reason when I added this modifier (Travelers belt (storage)) it works only like default one.

**Comment by xJon** [comment]
What do you mean that it works only like default one?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
