### ISSUE TITLE
I need help unlinking my inventory from a storage space [Hexxit II 1.4.0]

### ISSUE THREAD

**Issue by SapphicIndulgent** [xJon/Hexxit-II#175]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes 
- Pam's harvest craft & Mr Crayfish Furniture Mod
- **Crash/latest log link (if applicable)**: N/A

**Help needed**

So when I shift + right click (while holding a tinker's construct pickaxe) on any storage item that's been placed (storage drawer, chest), it gives me the chat message "Linked Inventory at [x= ,y= ,z= ] and dimension 0" with the x,y,z coordinates being filled out. 

And it looks like any blocks I get are instead instantly put into that storage item instead of in my inventory and I cannot find a way to turn it off or unlink it. Doing the same action again on the same storage item just gives me a repeat of that message. I don't know how to unlink it and I really really would like to not have all of my items go into that storage space instead of my inventory

**Comment by xJon** [comment]
I don't have too much experience with it, I think it's the Brown Magic modifier from PlusTiC. You may want to ask about it over the Modded Minecraft [Discord](https://discord.gg/moddedmc/) or [subreddit](https://www.reddit.com/r/feedthebeast)!

**Comment by SapphicIndulgent** [comment]
No it's not that. I don't have the Brown Magic modifier on the pickaxe, or in the pack in general

**Comment by xJon** [comment]
In this case I have even less of a clue what is happening. Perhaps something that you have equipped in your Bauble slot?

**Comment by ACGaming** [comment]
It‘s the `Global Traveller` modifier from PlusTiC. There‘s a keybind called `Toggle GUI` to disable this feature from your tool which defaults to the key `I`.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
