### ISSUE TITLE
Changelog for updated mods

### ISSUE THREAD

**Issue by UeberallGebannt** [xJon/Hexxit-II#176]
I already made an issue like this quite a while ago but I have to do it once more.
The changelogs don't include which mods have been updated which makes it hard to update the modpack servers if you don't want to just past the whole mod folder.

I used the Changelogger app before but it doesn't work anymore for me (it doesn't load).

Old issue: https://github.com/xJon/Hexxit-II/issues/35

**Comment by UeberallGebannt** [comment]
It just loads forever without anything happening when pressing "Continue"
![grafik](https://user-images.githubusercontent.com/50475262/183701671-b347df76-aa98-4e35-a02b-a360dec5d99c.png)

**Comment by xJon** [comment]
Unfortunately the Changelogger no longer works. You can use a compare tool such as [WinMerge](https://winmerge.org/) to see the changes :)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
