### ISSUE TITLE
Tinkers Construct Tool Leveling 

### ISSUE THREAD

**Issue by ThunderDuck1801** [xJon/Hexxit-II#178]
When leveling up tools/weapons/armor the level is capped at 3(adept) i know there are more levels i just dont know how to uncap it 
I've looked everywhere I don't know what to do
i am using java 8 64 bit
i have not added any other mods

**Help needed**

**Comment by xJon** [comment]
Hi, this is intentional! If you want to have more levels you can change the configuration of the mod in the config file.

**Comment by ThunderDuck1801** [comment]
> Hi, this is intentional! If you want to have more levels you can change the configuration of the mod in the config file.

Okay thank you for the answer the only problem is I don't know how to do that could you possibly help

**Comment by ACGaming** [comment]
Open the file `TinkerToolLeveling.cfg` (located in the config folder of the modpack) with a text editor of your choice. Change the value of `maximumLevels` (set to 3 in the modpack) to whatever you want.

**Comment by ThunderDuck1801** [comment]
> Open the file `TinkerToolLeveling.cfg` (located in the config folder of the modpack) with a text editor of your choice. Change the value of `maximumLevels` (set to 3 in the modpack) to whatever you want.

So i did that but i went back in game and its still not working i dont know why any clues

**Comment by ACGaming** [comment]
Could be that it only applies to new tools after changing the value.

**Comment by ThunderDuck1801** [comment]
i tried but new tools dont work either so i dont know what i did or am doing wrong

**Comment by ThunderDuck1801** [comment]
> 

I figured it out people told me to set the top value to 0 but that's wrong you have to do something higher I just put 1000 so I don't get  capped

**Comment by ACGaming** [comment]
You‘re right! I just checked the code and the value needs to be below zero (opposed to the config description), so `-1` should work for actual uncapped levels.
