### ISSUE TITLE
Quartz Dimensional Door pocket, no loaded textures

### ISSUE THREAD

**Issue by Lotzofblocks** [xJon/Hexxit-II#18]
**Basic details**
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: No
- **Crash/latest log link (if applicable)**: Not applicable

I placed a Quartz Dimensional Door and was able to enter and leave the pocket a few times without any trouble. After a few of these re-entries, none of the blocks in the pocket (mostly Altered Fabric, but also a few Tinker's benches, chest, and a Waystone) had any texture loaded. I would become stuck in place, and the world would just be pure white, unable to see any of the blocks I placed or for the box at the top of the screen to indicate I was looking at Altered Fabric (https://imgur.com/a/1l1mmdJ). During this, the block in my hand was visible, mostly under the screen, and would remain stationary as I rotated the camera. This would occur both entering the Quartz Dimensional Door from the Overworld, and an Iron Dimensional Door I placed inside the pocket after the bug started occurring. Relogging, I was able to move around again and have the info box indicate what blocks I was looking at, but every block was completely transparent, being able to see the skybox (https://imgur.com/a/JKoR7CK). I was able to seemingly randomly get individual chunks to render their textures by either breaking or placing blocks in the dimension (https://imgur.com/a/49DtDNK). Breaking, placing, or interacting with any blocks would also randomly get rid of the texture for any of the chunks I had gotten the texture for to load. This only seemed to work for the vertical chunk layer I was on and did not extend upwards to the ceiling. At this point I realized the Waystone I had placed had removed its activated texture, no longer showed the name I gave it when placing it, and that when right-clicking it, no menu was brought up, just particles around it and the exp sound effect (https://imgur.com/a/USjRE3y). By placing crafting grids on the ground, I found I was able to make adjacent chunks load textures while not having other ones randomly lose their textures (https://imgur.com/a/xWXYQ1w). When returning to the Overworld, it seems to either give me the bug that sticks me in place, with no visible textures requiring a relog or leave me just perfectly fine. I have not been able to understand what I do to cause the game to do either one of these options, same with the seeming randomness of being able to load and unload chunks' textures inside the pocket dimension. This has all taken place on a multiplayer server with no other players reporting similar bugs occurring, or any bugs or glitches occurring to them while I experienced this. At one point while typing up this report, the dimension seemed to allow me to return to the Overworld fine, and go back through the Quartz door to a bug-less Pocket Dimension. I am unsure what caused this to occur, but it only happened once over the course of a few hours.

**Comment by xJon** [comment]
Can you test whether this issue is still present with the latest version of the modpack? (`1.4.0`)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the requested info :)
