### ISSUE TITLE
Experience bug/Hero Medalien

### ISSUE THREAD

**Issue by SWTD** [xJon/Hexxit-II#181]
The Hero Medalien vanished from my inventory but still collects my exp
Are you using Java 8, 64-bit?: no i used Hexxit 2 in v1.12.2
Did you add any additional mods: no

The Hero Medalien vanished from my inventory but still collects my exp
with a second medalian you can store half of it and get it when you deaktivate it but only the experience from the medal
but if you die or clear your invetory the bug is still aktive and you cant get any exp

**Comment by xJon** [comment]
Do you have any steps for reproducing the issue?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info!
