### ISSUE TITLE
Entity Culling incompatibility with VoxelMap causing crashes 

### ISSUE THREAD

**Issue by Inflated-ballon** [xJon/Hexxit-II#182]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**:https://mclo.gs/pMonY8p

**Describe the issue**
When I play hexxit II it keeps crashing randomly sometimes I can only hexxit II for one minute sometimes I get lucky and I can play hexxit II for 30 minutes. As of today I played hexxit II  for a about 1 minute opened the map and then it crashed. I have included the crash link and the crash files as well.

[crash-2022-08-17_20.56.03-server.txt](https://github.com/xJon/Hexxit-II/files/9429807/crash-2022-08-17_20.56.03-server.txt)
[crash-2022-08-17_20.56.07-client.txt](https://github.com/xJon/Hexxit-II/files/9429808/crash-2022-08-17_20.56.07-client.txt)
[crash-2022-08-17_21.53.10-client.txt](https://github.com/xJon/Hexxit-II/files/9429809/crash-2022-08-17_21.53.10-client.txt)
[crash-2022-08-25_23.09.54-client.txt](https://github.com/xJon/Hexxit-II/files/9429810/crash-2022-08-25_23.09.54-client.txt)

**Comment by xJon** [comment]
Are you playing on a server, or singleplayer?

**Comment by Inflated-ballon** [comment]
I play single player

**Comment by xJon** [comment]
Do you know when this started to happen? Do you remember whether it started to occur after building or placing something new in your world?

**Comment by Inflated-ballon** [comment]
Well see this is what happened. So as of right now I have a new laptop and the same desktop. Now this world I had in my old laptop. So I backed up this world and put it on my New laptop and also in my desktop. 1 week later this started to crash on desktop. But now this world also crashes on my laptop. For clarification I have this world On my laptop and desktop. I backed this world from my Old laptop. I hope this doesn't confuse you. It also crashes sometimes when I open the map. Or I could just be walking , attacking some mobs.

**Comment by Inflated-ballon** [comment]
This world crashes on my new laptop and my desktop. If you'd like I can give you the crash files for this world from my new laptop as well

**Comment by xJon** [comment]
I see, yeah I'm not referring to the machine but to your world specifically. If you have any idea whether this crash started to happen in a specific area, or after building something in the world.

**Comment by Inflated-ballon** [comment]
As far as I can tell no. It can happen anywhere.

**Comment by Inflated-ballon** [comment]
I wasn't building anything either. Just standing still and I opened the map

**Comment by xJon** [comment]
Okay, thank you for the report! Will try to see what I can do regarding this issue. In the meantime you can remove either VoxelMap or Entity Culling to prevent the crash.

**Comment by Inflated-ballon** [comment]
Okay thank you

**Comment by Inflated-ballon** [comment]
So i have been more hexxit to see if it crashes and now its says other mods are the potential problem

**Comment by Inflated-ballon** [comment]
[crash-2022-08-26_20.16.56-client.txt](https://github.com/xJon/Hexxit-II/files/9437073/crash-2022-08-26_20.16.56-client.txt)

**Comment by ACGaming** [comment]
No VoxelMap involved in the last crash report. Can you test again with the latest versions of [RenderLib](https://github.com/Meldexun/RenderLib/releases/download/v1.12.2-1.1.7/RenderLib-1.12.2-1.1.7.jar) and [EntityCulling](https://github.com/Meldexun/EntityCulling/releases/download/v1.12.2-6.2.2/EntityCulling-1.12.2-6.2.2.jar)?

**Comment by Inflated-ballon** [comment]
How do I get the latest versions of Renderlib and EntityCulling installed

**Comment by xJon** [comment]
@Inflated-ballon You head over to the modpack's installation folder, and change the mods within the `mods` folder. You'll need to remove the old Entity Culling mod from there and install the 2 new files @ACGaming has linked.

**Comment by Inflated-ballon** [comment]
So I have been for a bit and so far no crashes.

**Comment by Inflated-ballon** [comment]
I even opened the map many times

**Comment by xJon** [comment]
With the latest version of RenderLib and EntityCulling?

**Comment by Inflated-ballon** [comment]
Yes

**Comment by Inflated-ballon** [comment]
It crashed again

**Comment by Inflated-ballon** [comment]
[crash-2022-08-28_11.28.01-client.txt](https://github.com/xJon/Hexxit-II/files/9440066/crash-2022-08-28_11.28.01-client.txt)
as soon as I opened the map

**Comment by xJon** [comment]
Thanks for the report! @ACGaming is working on a special mod that will try to fix this incompatibility.

**Comment by Inflated-ballon** [comment]
Okay thank you

**Comment by xJon** [comment]
Unfortunately it seems that it'd be impossible to fix this incompatibility without rewriting some parts of VoxelMap.
If you keep experiencing this crash, feel free to manually remove either VoxelMap or Entity Culling.

**Comment by Inflated-ballon** [comment]
Okay

**Comment by xJon** [comment]
This will be fixed in the next modpack update thanks to [this update](https://github.com/ACGaming/VoxelMapFixes/releases/tag/1.12.2-1.0.7) to VoxelMapFixes.

**Comment by xJon** [comment]
This is resolved in version `1.4.3` of the modpack thanks to @ACGaming :)
