### ISSUE TITLE
Server Mod Rejections

### ISSUE THREAD

**Issue by AgmonBlynkos** [xJon/Hexxit-II#183]
Basic details
- Are you using Java 8, 64-bit?: yes
- Did you add any additional mods?: no
- Crash/latest log link (if applicable): not applicable

Server Mod Rejections:
GeckoLib: Requires version 3.0.29 but client has 3.0.30.
Jon's Exclusives: Requires version 1.1.1 but client has 1.1.2
![requires](https://user-images.githubusercontent.com/108335762/187297419-c1096fea-bba5-4388-96b1-8fd5362c2a32.png)

**Comment by xJon** [comment]
You need to make sure both the server and the client are using the same version of the modpack.

**Comment by AgmonBlynkos** [comment]
me and my friend both have the latest 1.4.1 version of the modpack but this keeps appearing

**Comment by xJon** [comment]
What about the server?

**Comment by AgmonBlynkos** [comment]
we got the server files from the official technic platform

**Comment by AgmonBlynkos** [comment]
ok the server mods were outdated for some stupid reason, it works now you can close the thread

**Comment by xJon** [comment]
Glad you got it working, enjoy playing :)
