### ISSUE TITLE
cant join server

### ISSUE THREAD

**Issue by YUNGmo69** [xJon/Hexxit-II#184]
<!--
hey guys 

me and my friends startet to play on a server from my friend and after 1 day there was a problem.
only me have the problem . i cant join a server i get kicked when i join the server . i use java 64bit and we play hexxit 2 version 1.40 with mods . and then

![Anmerkung 2022-10-08 221647](https://user-images.githubusercontent.com/115498132/194930876-92fdabf6-b9ff-44f0-91d2-2a2672afb5b7.png)
![{11592574-3E52-4AD5-ADD7-2141BF8333BD}](https://user-images.githubusercontent.com/115498132/194930900-4c8a22e8-1f61-48d4-b26b-a12bee8e1fcb.png)
 ,, connection lost internal exception io.netty.handler.codec.decoder. java.langRuntimeException; tried to read NBT tag that was too big; tried to alocate: 16777239bytes where max allowed 16777216 .

what does that mean pls help me guys

**Comment by xJon** [comment]
Which server?

**Comment by xJon** [comment]
Closed due to inactivity.
