### ISSUE TITLE
Server crashes on launch

### ISSUE THREAD

**Issue by OhFlohre** [xJon/Hexxit-II#186]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Error message**: https://pastebin.com/Dr0hLHba

**Help needed**

When starting a server on my linux server with the LaunchServer.sh I just get the error message from the link obove.
I tried starting it on my windows machine using the .bat file but got the same error.

**Comment by OhFlohre** [comment]
Okay thanks but how do I do that?

**Comment by OhFlohre** [comment]
Just tried it with jdk-19, same error

**Comment by ACGaming** [comment]
None of that, Java **8**!

**Comment by OhFlohre** [comment]
Oh me stupid. Got it, thanks <3
