### ISSUE TITLE
Crash on Load - Fresh Install

### ISSUE THREAD

**Issue by AceSardonyx** [xJon/Hexxit-II#188]
I am using Java 8 which is managed by curseforge app anyways
I did not add anything, I just downloaded this today
https://mclo.gs/RNWgAT2 - It said it encouraged me to send this, so here it is.

Not sure how to describe it, I just downloaded the pack today and uhh yeah....
Maybe this will help: https://i.imgur.com/BMCoPuG.png

Help would be greatly appriciated.
I was told that there were mods in this pack that were used in the creation of a neat lil horror series on youtube called The Haunting by RejectedShotgun on youtube. I found a lot of interest in the way they used these mods to create their story. I would like to try out this modpack a lot with that being said 😄

**Comment by xJon** [comment]
This doesn't seem like Hexxit II unfortunately, sorry!

**Comment by xJon** [comment]
Happy you resolved it :)
