### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by TAGB0T** [xJon/Hexxit-II#189]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**:  latest log: https://mclo.gs/WJRR7S0  crash: https://mclo.gs/Sgdl4QN

Everytime i try to start the game it just crashes. Idk what i did wrong or what the problem is. I hope someone can help me with it. Thanks in advance. ^^

**Comment by ACGaming** [comment]
Looks like it‘s GPU-related. What GPU do you have and have you already tried to update your graphics drivers?

**Comment by TAGB0T** [comment]
Ok i found the error. The onboard GPU of my Laptop was deactivated. Seems like MC dosen't like that. I activated it and now it works... I feel kinda dump right now. Thank you very much

**Comment by ACGaming** [comment]
Glad it‘s something simple, enjoy!
