### ISSUE TITLE
adding optifine breaks fire animations

### ISSUE THREAD

**Issue by SilverDarkBlade** [xJon/Hexxit-II#194]
when i add optifine, fire anims freeze. i have checked the animation settings in optifine and they are all enabled. smart animations is disabled.

nether portal animation is also broken.

**Comment by ACGaming** [comment]
When using OptiFine, set the value of `onDemandAnimatedTextures` (line 329) in `loliasm.cfg` to `false`.

**Comment by SilverDarkBlade** [comment]
this fixed it, thank you!
