### ISSUE TITLE
New version of Recurrent Complex issues with hybrid servers and OpenJ9

### ISSUE THREAD

**Issue by Zilacon** [xJon/Hexxit-II#197]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes (but were disabled for testing, issue persists with all of them disabled)
- **Server Jar:** Catserver/Mohist/Magma 1.12.2 (tested all of them)

So 1.4.5 for me is a complete disaster. RecurrentComplex was updated to a broken build, this build has an issue with openj9 with its shadow jar, which has an incorrect path when its compiling on server start up. This was not an issue with prior versions. The second issue is that now recurrentcomplex requires it to be on the client now, it has always been a server only mod up until now, so the obvious solution to this problem would be to just disable the mod serverside, but i cannot due to it now being required on the client, players cannot join.

And then switching to hotspot, recurrentcomplex works on hotspot, but now CQR does not work on hotspot, its throwing errors about loading protection region data on login and is cancelling the player login. This issue does not occur when using Openj9, so im in a loop of issues, it doesnt matter if i use normal java, or openj9 as theres 2 issues with 2 mods preventing the use of both of them.

When joining with hotspot you get this error from CQR:
https://mclo.gs/GGIKJl7

When loading with openj9 you get this error from recurrentcomplex:
https://mclo.gs/Pi0R7bS

Entire crash logs for both mods:
[crash-2023-03-29_21.37.56-server.txt](https://github.com/xJon/Hexxit-II/files/11114973/crash-2023-03-29_21.37.56-server.txt)
[crash-2023-03-30_11.38.09-server.txt](https://github.com/xJon/Hexxit-II/files/11114974/crash-2023-03-30_11.38.09-server.txt)

Yes there are added mods in both crash reports, ive spent 2 days disabling everyone of my other included mods checking to see if they are the cause of the problem, with all of them disabled there was no change in issues, so none of the additional mods seem to be the cause.

**Comment by Rishum-P** [comment]
[reccomplexdummy.zip](https://github.com/xJon/Hexxit-II/files/11115707/reccomplexdummy.zip)

@Zilacon Above is a dummy mod you can replace Recurrent Complex server-side that will allow players to join despite the mod being removed. It should at least be a temporary solution especially given your world's likely pre-generated anyway.

**Comment by Kennedi31** [comment]
My game keeps crashing and will not let me continue to play because of these mods. I do not understand how to fix this. Please help me fix this problem.

**Comment by Rishum-P** [comment]
> My game keeps crashing and will not let me continue to play because of these mods. I do not understand how to fix this. Please help me fix this problem.

Please upload a log

**Comment by xJon** [comment]
@Kennedi31 Please open a new issue for help :)
Regarding the current issue, I'm closing this as we've found workarounds (including https://github.com/Ivorforce/RecurrentComplex/pull/494)
