### ISSUE TITLE
Hexxit 2 forge server crash

### ISSUE THREAD

**Issue by evarinli** [xJon/Hexxit-II#198]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods** /no
- **Crash/latest log link (if applicable)**: in attach

Hello guys yesterday i created a minecraft forge server its keep crashing why is keep crashing anyone help me pls

[crash-2023-04-12_03.00.42-server.txt](https://github.com/xJon/Hexxit-II/files/11216017/crash-2023-04-12_03.00.42-server.txt)

**Comment by xJon** [comment]
Can you tell me how did you setup the server? How did you do it?

**Comment by evarinli** [comment]
first i install forge 1.12.2 recomm vers after click the minecraft 1.12.2 named file after accept eula after startup forge and get mod world etc. folder goto appdata copy all hexxit mods paste server mods folder use jar nogui command give to the ram to server and click launch

**Comment by xJon** [comment]
@evarinli That's not the recommended way of doing it - you can download the server package for Hexxit II :)
https://servers.technicpack.net/Technic/servers/hexxit-2/Hexxit-II_Server_v1.4.5.zip

**Comment by evarinli** [comment]
> @evarinli That's not the recommended way of doing it - you can download the server package for Hexxit II :) https://servers.technicpack.net/Technic/servers/hexxit-2/Hexxit-II_Server_v1.4.5.zip

thanks man a lot its worked

**Comment by xJon** [comment]
So glad! Feel free to ask if you need any further help :)

**Comment by evarinli** [comment]
> So glad! Feel free to ask if you need any further help :)

john 1 more issue i hosted the server but my friends cant join server we use hamachi any advice or hamachi alternative

**Comment by evarinli** [comment]
how to my friends join me whats your way

**Comment by xJon** [comment]
Hey! Hamachi is not really recommended. Best would be opening ports when self-hosting, or using a paid hosting service. If you want to host on your machine I advise you to Google instructions for opening ports or asking over Technic's Discord server :)

**Comment by evarinli** [comment]
how to open self port can you link the video pls

**Comment by xJon** [comment]
It depends on your router, so I recommend you to search in Google or Youtube for instructions!

**Comment by ACGaming** [comment]
You can also play via `Open to LAN` using your Hamachi IP addresses. Works like a charm for most modpacks.
Radmin VPN and ZeroTier are viable alternatives to Hamachi.
