### ISSUE TITLE
Backpacks Not Working Properly

### ISSUE THREAD

**Issue by CloudySkye02** [xJon/Hexxit-II#199]
**Basic details**
- **Are you using Java 8, 64-bit?**: Unsure using 1.4.5
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: not applicable

Game only allows you craft 1 Large backpack. It also does not allow you to have any more then the one active backpack. It does not show up in the crafting table and if you cheat one in it does not let you open said back pack.

**Comment by xJon** [comment]
> Game only allows you craft 1 Large backpack.

I tried crafting multiple Big Backpacks and was able to do it. Did you mean something else?

> It also does not allow you to have any more then the one active backpack

Do you mean in the Backpack Slot? That is intended, although you can always use multiple backpacks by manually opening them in your inventory.

> It does not show up in the crafting table

What do you mean? I can't reproduce this.

> if you cheat one in it does not let you open said back pack

That's a quirk of the mod, but you can cheat in the backpack parts and manually craft their last stage.

**Comment by CloudySkye02** [comment]
> 
Game is newly updated, I uninstalled and reinstalled Hexxit 2 and the same issue is popping up, it will not allow to craft a second LG back pack. I am doing it correctly it just is refusing to work. I attached a picture of the crafting table showing that the backpack is not popping up.
![image](https://user-images.githubusercontent.com/131511879/233816939-666e136f-20d1-469c-83a2-92d2fe5ddab4.png)

**Comment by xJon** [comment]
@CloudySkye02 Are all of the pieces of the same tier?

**Comment by CloudySkye02** [comment]
They were, I just fixed it by using different tiers and it allowed me to craft backpacks again

**Comment by xJon** [comment]
Strange. Can you reproduce the issue? Can you explain how?

**Comment by CloudySkye02** [comment]
Yes I'm able to recreate it, it seems that after I made the first large backpack with the wooden sticks it will not allow me to make another large backpart with the base made of wooden sticks entirely. I'm able to mix and match with the stone and iron sticks or simply use iron and the stone to create large backpacks. So I suppose the wooden tier is acting a bit off

**Comment by xJon** [comment]
Oh I see that sometimes when using the Wooden Frame, it might sometimes detect it as frame tier III and sometimes as tier I, so mixing them does not work. A bit off indeed. Is that the issue you're referencing?

**Comment by CloudySkye02** [comment]
No it's a bit opposite, just not letting me craft a lg backpack with the wood a second time but allowing me to mix and match all I please

**Comment by xJon** [comment]
That's odd, I can't reproduce this unless I misunderstand you. Perhaps you can include a short video, but it seems this is a rather minor issue?

**Comment by xJon** [comment]
Closed due to inactivity (will reopen if requested).
