### ISSUE TITLE
CQR Muskets delete off-hand items

### ISSUE THREAD

**Issue by EnderT5** [xJon/Hexxit-II#2]
Please fill in the following information.

**Basic details**
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: No
- **Crash/latest log link (if applicable)**:

Client Log: https://zerobin.net/?23d545d853b74529#i7wy3l5yUIIhr8T2v8edTFb/uKYfM8WD4B5Kj4r2/ow=
Server Log: https://zerobin.net/?4894450f6697bb6d#c/wadpab+u71afd3pDUPo/LrtxWJY1aviOQf3Utoh8o=

**Describe the issue**

If you are holding a Musket with a Monking Dagger, your off-hand items will be automatically deleted.

IMAGE: https://imgur.com/a/f2aZvo0

**Comment by xJon** [comment]
This is fixed in the latest update :)
