### ISSUE TITLE
Growthcraft Bee Boxes won't fill completely

### ISSUE THREAD

**Issue by HenryNautilus** [xJon/Hexxit-II#200]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: yes, Optifine.
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Growthcraft beeboxes don't seem to ever fill with honey. Only half-way.
![2023-04-22_23 44 51](https://user-images.githubusercontent.com/48847670/233819510-74a9c36b-ecbf-4b19-880d-cbf4a349839a.png)
![2023-04-22_23 44 58](https://user-images.githubusercontent.com/48847670/233819511-e37448ee-56d2-4944-be68-633a5799b856.png)

This has been happening both on singleplayer and a server. I have used multiple types of vanilla minecraft flowers. Gave them ample room. They have max bees. (I am unsure if they are even supposed to fill all the comb, but I'm guessing this is a bug.) Am I missing something and they can be upgraded? Wikis have been rather unhelpful.

Ta

**Comment by xJon** [comment]
Fixed in update `1.5.0` thanks to @ACGaming :)
