### ISSUE TITLE
game and pc freeze when a save is opened for the second time

### ISSUE THREAD

**Issue by DeusMortem0** [xJon/Hexxit-II#202]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: https://mclo.gs/rx35FF7

**Help needed**

When I create a new world, I can play for hours without issue, but when I rejoin the same world, after a few minutes, the game and even my computer freezes completely.

Some things I've tried:

Since there are lines about the mocreatures mod at the end of the log file, I tried removing the mod and re-entering it, but this time the game did not open at all. If you want I can do this again and attach the log file.

I tried to download version 1.4.4 and enter but same problem

I downloaded [deuf ](https://www.curseforge.com/minecraft/mc-mods/deuf-duplicate-entity-uuid-fix)mod but still the same

**Comment by xJon** [comment]
- Is the linked log of the game session that ended in freezing?
- When the game freezes, I'd love for you to fetch a "thread dump", to better understand what's happening, as the log is unclear. To get it:
      1. Download and install Java 8 JDK from https://adoptium.net/temurin/releases/?version=8
      2. Start the game and wait for it to freeze
      3. Once it freezes, get the game's PID number from task manager (by enabling the PID column with a right click)
      4. Open Command Prompt, and type `jstack <PID value>` (without `<>`)
      5. Copy what's printed to https://mclo.gs/ and share it here.

**Comment by DeusMortem0** [comment]
unfortunately the command can't print anything because the computer also froze

**Comment by xJon** [comment]
What do you mean? You can't use the computer whatsoever?
Is that always the case?

**Comment by DeusMortem0** [comment]
the computer is very slow. I can only do simple things and most apps are not responding. I have to restart the computer to fix it.

**Comment by xJon** [comment]
Does this occur with other modpacks as well, such as Hexxit II or other ones from the Technic Launcher or other launchers (such as CurseForge)?

**Comment by DeusMortem0** [comment]
I don't know. Is there a modpack you can recommend for me to try this?

**Comment by xJon** [comment]
Tekkit 2 and The 1.12.2 Pack have a lot of overlapping mods to Hexxit II as I have made all three.
You can try Tekkit 2 in the Technic Launcher (it's listed by default), and maybe you can try The 1.12.2 Pack over CurseForge (albeit being available through Technic) to check whether there's a difference in the launcher: https://www.curseforge.com/minecraft/modpacks/the-1122-pack

**Comment by DeusMortem0** [comment]
I tried tekkit 2 and there is no problem

**Comment by xJon** [comment]
Well that's good. Unfortunately I don't really know beyond that what to suggest for Hexxit II though without any log error or thread dump.
One thing you can do is experimenting with removing mods and seeing whether removing a particular mod or mod combination resolves your issue. It's a pain but a last resort.

**Comment by xJon** [comment]
Is this thread dump from when the game was running or from when it was frozen?

**Comment by DeusMortem0** [comment]
when the game freezes

**Comment by xJon** [comment]
Closed due to inactivity (will reopen if requested).
Also worth trying out with the new update.
