### ISSUE TITLE
Sprinklers from Openblocks not working

### ISSUE THREAD

**Issue by cranss** [xJon/Hexxit-II#204]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Sprinklers from Openblocks are not working, particles in video options are activated but there's no animation, also it doesn't water the blocks around it, and when you right-click on it, to add mealbone, the inventory screen of the sprinkler closes immediately.

**Comment by xJon** [comment]
Thank you for the report, it will be fixed in the next update :)

**Comment by xJon** [comment]
Fixed in update `1.5.0` :)
