### ISSUE TITLE
Although I have 8 GB of ram, there is a maximum of 1 GB option, someone who knows how to fix this, please help

### ISSUE THREAD

**Issue by Yarragiminbashi** [xJon/Hexxit-II#205]
![ramm](https://github.com/xJon/Hexxit-II/assets/142609563/7b58fcc1-9000-40a7-a1ae-c81c68b9d865)
![ram](https://github.com/xJon/Hexxit-II/assets/142609563/d18709b7-452f-4337-ba38-24b3ade5a12e)
 help me pls

**Comment by xJon** [comment]
You need to install Java 8 64-bit.

**Comment by xJon** [comment]
Closed due to inactivity.
