### ISSUE TITLE
I crash when joining my private 1.5 server 

### ISSUE THREAD

**Issue by PandaFs23** [xJon/Hexxit-II#206]
**Basic details**
- **Are you using Java 8, 64-bit?**: no / yes Y
- **Did you add any additional mods**: yes (detail) / no  N
- **Crash/latest log link (if applicable)**: link to log / not applicable 
https://mclo.gs/4Pxhgwg
https://mclo.gs/APJEnB3

**Help needed**

A clear description of what help is needed.

**Comment by PandaFs23** [comment]
Super weird. My server doesn't crash and runs smooth. Just whenever I join it I crash....weird

**Comment by xJon** [comment]
Perhaps it's a crash regarding `Snow! Real Magic!` mod, can you try removing it from the server side and try again?

**Comment by PandaFs23** [comment]
Hello, 

I just tried a new world on the server and it worked. kinda sucks but I am very Happy with the update. I am going to just start fresh! Thank you for the support! seriously great mod pack

**Comment by xJon** [comment]
I'm happy you're enjoying it! If you do want to use the old world, troubleshooting _should_ resolve it, but it's your choice :)
Feel free to write here if you want to troubleshoot further.
