### ISSUE TITLE
Secret rooms 5 One-Way Glass crashes world upon placement.

### ISSUE THREAD

**Issue by RSRampage01** [xJon/Hexxit-II#208]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://pastebin.com/f6VTNGpS

**Describe the issue**

If you place a One-Way Glass block from the mod Secret Rooms 5, The world immediately permanently freezes. If you try to reopen the world after closing it, the world immediately crashes.

**Comment by xJon** [comment]
I can't see the crash log, as it's set to private.

**Comment by RSRampage01** [comment]
> I can't see the crash log, as it's set to private.

I can't un private it because loli is one of the modpack components and that is a blacklisted word on pastebin. Is there any way to get around this?

**Comment by RSRampage01** [comment]
> I can't see the crash log, as it's set to private.

Fixed I hope

**Comment by xJon** [comment]
Can you try updating the modpack to its latest version (`1.5.1`)?
