### ISSUE TITLE
Game frozen after coming out of Nether

### ISSUE THREAD

**Issue by xiaoxinny** [xJon/Hexxit-II#213]
**Basic details**
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: No
- **Crash/latest log link (if applicable)**: Not applicable, but screenshot of console attached

**Describe the issue**
Recently, after a long expedition to the nether, I had tried to return home via the portal I've entered from in the first place. 
However, though the overworld renders as I return, nothing can be done with effect, meaning armor does not show that I have armor even if its worn, mining anything won't yield the drops, any accessible block such as part builder or chests will not work, and the game is practically frozen in place. 
I've tried to rectify this by restarting the game twice, and even tried to restart the launcher and PC, all to no avail.
When backed up from a restore, I was able to make some progress and made it out of the nether, but soon there was a severe delay in TPS and latency, and the whole game is frozen yet again while I was able to move around.

Here's the screenshots for the console logs:
![Screenshot 2023-10-01 021840](https://github.com/xJon/Hexxit-II/assets/106980227/ed0f1035-2654-4b69-a756-2c25a0e32d0b)
![image](https://github.com/xJon/Hexxit-II/assets/106980227/0981b54a-c8cf-4643-be89-4cbad8b88d3c)

**Comment by xJon** [comment]
Can you try to disable the Dynamic Lights mod? Either by pressing `L` in-game or by removing the mod file.

**Comment by xiaoxinny** [comment]
> Can you try to disable the Dynamic Lights mod? Either by pressing `L` in-game or by removing the mod file.

I've disabled it and have been playing for a few hours, and things have been fine for now. Though curious, appears that this mod bugs the game out?

**Comment by xiaoxinny** [comment]
Update: With Dynamic Lights off, I made another trip to the nether. However, this time, the error happened again, and my whole world is frozen except for me. 
I have uninstalled the mod for Dynamic Lights and tried doing the same thing, but it still freezes the world.
I saw in the console that the Mega Torch could have caused this error, so I broke it while the world was frozen, hoping it might resolve itself after a restart.
Well.. that may have been a mistake as now the world has become inaccessible, and the game simply crashes every time I try to enter, or even accessing from a backup.
Here is the crash log: 
https://mclo.gs/iAbYBYC

**Comment by xJon** [comment]
How did you load a world backup? It should be unaffected - did you use the `RestoreBackup.bat` script?

**Comment by xiaoxinny** [comment]
> How did you load a world backup? It should be unaffected - did you use the `RestoreBackup.bat` script?

I restored it via the in-game option to restore from backup when selecting worlds, and restored to about 1 hour before the issue

**Comment by xJon** [comment]
Right, you're playing singleplayer. I'm really sorry about this experience, it's really odd. Have you tried restarting the game and trying again to load a backup? Have you tried loading an even earlier backup, or perhaps just entering the backup and seeing if it works?

**Comment by xiaoxinny** [comment]
I have tried restarting the game and tried to enter a backup that was 8 hours prior to the crash, still the same issue of world being frozen, except I was able to enter the game unlike the current situation. 
I do have the game log now as I have replicated the issue without Dynamic Lights installed in the game when entering the backup.
![image](https://github.com/xJon/Hexxit-II/assets/106980227/15cd3af9-b130-4eb7-8ad6-b18d0fbb8a54)
[latest.log](https://github.com/xJon/Hexxit-II/files/12779932/latest.log)

This is the log from going into creative world, for which before I could even do anything other than taking materials from the creative menu, the game has already timed out itself:
![image](https://github.com/xJon/Hexxit-II/assets/106980227/e208ff79-5ed5-4d66-828c-9d73a34f44e3)

**Comment by xJon** [comment]
I can't tell an issue from the log. You could try a couple of things:
- Thread dump when the game is frozen. To get it:
      1. Download and install Java 8 JDK for your system from https://adoptium.net/temurin/releases/?version=8
      2. Start the game and wait for it to freeze
      3. Once it freezes, get the game's PID number from task manager (by enabling the PID column with a right click)
      4. Open Command Prompt, and type `jstack <PID value>` (without `<>`)
      5. Copy what's printed to https://mclo.gs/ and share it here.
- Use `spark` to profile the game. To get it, simply download [this version](https://www.curseforge.com/minecraft/mc-mods/spark/files/3245793) and put it in the `mods` folder. In-game, do `/spark profiler`. There might a better command for this though, I'll inquire. I'm also not sure this can work if the game is freezing.

**Comment by xiaoxinny** [comment]
I have tried to obtain a thread dump using Jstack, but I get this error:
![image](https://github.com/xJon/Hexxit-II/assets/106980227/a30183fe-3054-4719-870d-6ef798778f8d)

Using Spark does not work as well, as right now the game crashes so hard I can't even get Technic Launcher to work after it crashes, and when frozen no commands can be delivered (I am running this on Win11, so no async-profiler).

I did not find a debug.log file inside the logs folder though after searching through Hexxit files. Should it be there?

One other thing to note is that, whenever I am launching Hexxit, it takes 2 tries to launch the game, and the first try often fails to launch the game. 

Running Tekkit on the other hand has been perfectly fine. Although I still get the "Can't keep up?" logs, but the game has never frozen nor crashed, even with massive entity spikes.

**Comment by xiaoxinny** [comment]
> This might be too obvious but have you tried doing a clean reinstall of Hexxit II?

Could I do such by saving the 'saves' folder elsewhere, and replacing it back after reinstalling hexxit? Or would that cause any conflict?

**Comment by ACGaming** [comment]
This works, yes.

**Comment by KorewaLidesu** [comment]
Can you send the spec of your computer?
> as right now the game crashes so hard I can't even get Technic Launcher to work after it crashes

This seem odd tho

**Comment by xiaoxinny** [comment]
> Can you send the spec of your computer?
> 
> > as right now the game crashes so hard I can't even get Technic Launcher to work after it crashes
> 
> This seem odd tho

That was one occurence using Spark. but it didn't happen afterwards.
My specs are currently:
Ryzen 5 5600G
16GB 3200Mhz RAM (10GB allocated to game)
RTX 3060Ti
Win 11 Home
Toshiba 2TB HDD
WD Black SN850 500GB SSD (Installation location)
Micron 250GB SSD
Any other specs you may require?

**Comment by xiaoxinny** [comment]
I have tried to reinstall the modpack, copy and pasted the saves folder over.
I feel like it is freezing even harder now, freezing without even requiring me to do anything in the game. 
This is the current log after a reinstall:
![image](https://github.com/xJon/Hexxit-II/assets/106980227/fb3ed74b-3d5f-40d4-92d9-da981de33a70)

Apologies but I also realised the instance in which it crashed both the game and the launcher was because I had used jstack commands.

**Comment by xJon** [comment]
How long did you wait for the game to "catch up" or "unfreeze"?

**Comment by xiaoxinny** [comment]
> How long did you wait for the game to "catch up" or "unfreeze"?

Apologies for the late reply, I have launched an instance, waited for it to crash, and have waited for about half an hour with no indication that it might be resolved. The logs and console also tell me nothing why this has occurred, not even a "Can't keep up?" message.

**Comment by xJon** [comment]
I'm not really sure what's happening. Have long have you played Hexxit II without this issue happening?

**Comment by xiaoxinny** [comment]
> I'm not really sure what's happening. Have long have you played Hexxit II without this issue happening?

I think since I started Hexxit II only recently, within 3 to 4 days of me playing consistently everyday.

**Comment by xJon** [comment]
Apologies for the late response.
Overall, I'm not sure how to further help, I'm sorry about that!
Usually log errors, thread dumps, and profiling tools help identifying causes of issues, and most people are able to play Hexxit II. Usually a clean reinstall or reverting to world backups are helpful in exceptional situations.
You might want to further attempt to use world backups and/or reinstall the modpack, you can also try to contact Technic's support in their Discord (https://discord.com/invite/technic). You can also try again to use [spark](https://www.curseforge.com/minecraft/mc-mods/spark/files/3245793) or perhaps [LagGoggles](https://www.curseforge.com/minecraft/mc-mods/laggoggles/files/4493884) (alongside [TickCentral](https://www.curseforge.com/minecraft/mc-mods/tickcentral/files/3140670)).

**Comment by xJon** [comment]
Closed due to inactivity, will reopen if requested.
