### ISSUE TITLE
my game is crashing after i joining my server. 

### ISSUE THREAD

**Issue by Papxx** [xJon/Hexxit-II#215]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes only Optifine 
- **Crash/latest log link (if applicable)**: https://mclo.gs/KgVDTF1

**Help needed**

After joing my server with the modpack installed the game crashes. Im playing version 1.4.4 because on my server hoster website hasnt the new versions on there side.

**Comment by xJon** [comment]
I highly recommend you to update the modpack due to all of the new features and improvements of the latest version. You could try contacting the server host and request them to update.
Beyond that, I'm unfamiliar with the crash - maybe you can reset the key bindings.

**Comment by xJon** [comment]
Closed due to inactivity, will reopen if requested.
