### ISSUE TITLE
I cannot start the game.

### ISSUE THREAD

**Issue by IloveTruffle** [xJon/Hexxit-II#217]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: link to log  https://mclo.gs/RbJMMX5

**Help needed**

A clear description of what help is needed.

**Comment by xJon** [comment]
Can you try to delete the file mentioned in this line and see if the issue is resolved?
https://mclo.gs/RbJMMX5#L58

**Comment by IloveTruffle** [comment]
I could, but would that not delete the world overall? I apologize for not explaining things, but I can play the mod just fine on other worlds. It's only this one that crashes.

**Comment by IloveTruffle** [comment]
I was able to fix my problem, since my world had backups. I simply restored my most recent backup and that allowed me to keep on playing and saving my world. It's probably temporary, but that's plenty. Thanks.

**Comment by xJon** [comment]
@IloveTruffle Deleting that single file should not reset your world, but only your Chocolate Quest Repoured Reputation data, which is not critical. Either way I'm glad you figured out another solution :)
