### ISSUE TITLE
Hello! I've been trying to install optifine but when I copy the file into the mods folder the modpack doesn't even start anymore, is there another way to install optifine to get some shaders?

### ISSUE THREAD

**Issue by voidxles** [xJon/Hexxit-II#22]
**Basic details**
- **Are you using Java 8, 64-bit?**: no / yes
- **Did you add any additional mods**: yes (detail) / no
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Help needed**

A clear description of what help is needed.

**Comment by Vanillequark** [comment]
@xJon, thanks.
Version `G5` works fine, for me at least.
