### ISSUE TITLE
Inventory Crafting Off-Center

### ISSUE THREAD

**Issue by MagicMason1000** [xJon/Hexxit-II#236]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

The crafting menu in the inventory is off-center. It seems to be stuck in the mode where the Cosmetic Armor section is open even when it isn't.

When the cosmetic armor menu is open:
![Crafting Normal](https://github.com/xJon/Hexxit-II/assets/46111269/457ad5a1-bd7b-4d24-8500-09c4f8913fd9)

When it is closed:
![Crafting Broke](https://github.com/xJon/Hexxit-II/assets/46111269/970280f5-4432-4dc8-ab08-982b11185d3f)

Crafting still works as intended, it's just the UI that's a bit broken. I'm surprised I haven't seen other issues opened about this though, I'm hoping it's not just me.

**Comment by xJon** [comment]
Strange, the crafting grid is not supposed to move when opening the Cosmetic Armour options. I am unable to reproduce this issue.
Do you have any steps for reproduction in a new world?

**Comment by MagicMason1000** [comment]
I just tried created a new world in creative and I still seem to have the issue. I don't have any reproduction steps because it seems to always be an issue that I can't get to go away. I've been trying to mess with some inventory settings to see if I can fix it, but no luck. I also forgot to mention in the original post (my bad) that I have not messed with any of the mods in the pack.

Something I did just barely notice is that there's a weird "Show Recipes" option that appears when I hover between the grid and the output. It's only there when it's in the broken mode.
![image](https://github.com/xJon/Hexxit-II/assets/46111269/bbb8bc54-0f74-462b-b1d9-d776637d69cf)

It opens this screen:
![image](https://github.com/xJon/Hexxit-II/assets/46111269/66f397cb-c9f1-446b-96b1-a9b4113d8233)

One more piece of info, it works fine when I open the Baubles menu as well. It seems to have some sort of default set to have these menus closed, so when I close the inventory and re-open it, it's always back in this broken state.
![image](https://github.com/xJon/Hexxit-II/assets/46111269/436db02b-0c6b-42b3-881d-f49a4f5c8e65)

Let me know if there's any more info you'd like me to grab, and sorry about the delayed response :)

**Comment by MagicMason1000** [comment]
Right after posting that last comment, I discovered the problem. Turns out the game was trying to load a resource pack I use for unmodded Minecraft which was screwing up the crafting grid. I didn't even realize it could do that lol. When you mentioned that you could reproduce it, I started looking for anything that I may have had different from you and looking in my resources and found that out. Sorry for wasting your time!!

**Comment by xJon** [comment]
No worries! Glad you figured it out and I appreciate the bug report (even if it turned out to not be caused by the modpack).
