### ISSUE TITLE
Too many Fireflies and Mimicrabs

### ISSUE THREAD

**Issue by kindruthecow** [xJon/Hexxit-II#238]
### Was this help requested before?

- [X] No, it was not.

### Please describe what you need help with

Not exactly a bug, but it's insane how many fireflies are in my game. The mimicrabs are pretty bad too, but I am trying to make a map that will one day be a hit, but the fireflies are making it unplayable. I do have many biomes, but if there is a way to turn down the spawn rate, or control the spawn rate, I would love to know. Whatever solution it is, I would mainly like it not just be client side, I want it to be permanent in the files of my map, so others don't experience this problem when playing it as well.

![2024-05-18_22 57 37](https://github.com/xJon/Hexxit-II/assets/68298334/d2c03dba-85a8-4f9f-a52d-b1db5b77c4b0)
![2024-05-18_23 03 09](https://github.com/xJon/Hexxit-II/assets/68298334/6162f365-56a2-472f-9a15-9e2463b72c1f)

**Comment by xJon** [comment]
Hi! You can configure and control the spawn rates of both the Fireflies and Mimicrabs, but unfortunately I'm not aware of a way of doing this per save, unless you ship the map as a multiplayer package which already has the config files pre-modified. If you ship it to be played in singleplayer, you could include pre-modified configs with instructions for players to paste and override them on the client side.

_For Fireflies_:
In `\modpacks\hexxit-ii\config\incontrol\spawn.json` in this block:
```
	{
		"mod": "lumen",
		"mincount": {
			"mod": "lumen",
			"amount": 360,
			"perchunk": true
		},
		"result": "deny"
	}
```
Try lowering the `amount` value.

_For Mimicrabs_:
Try lowering the `mimicrab spawn rate` and potentially `mimicrab spawn rate near player death` values in `\modpacks\hexxit-ii\config\Fishs_Undead_Rising.cfg`.

**Comment by kindruthecow** [comment]
Thank you for your help, less than 3 minutes ago i just discovered a fix. My best option was changing the biomes of my islands to not be any kind of forests, or swamps, and it did the trick!

**Comment by xJon** [comment]
@kindruthecow That's a clever workaround for the Fireflies, good job 💯
