### ISSUE TITLE
Chocobo Multiplayer Bug

### ISSUE THREAD

**Issue by NopeNopeNope2** [xJon/Hexxit-II#24]
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Description**
Breeding Chocobos on multiplayer results in immediate birth of a full grown yellow chocobo, even with carob nuts, making further variations unobtainable. It will always result in a yellow chocobo. This issue was found on the Complex Hexxit II server if you wish to verify.

**Comment by xJon** [comment]
Can you not reproduce this bug in singleplayer?

**Comment by NopeNopeNope2** [comment]
No, I tested it on singleplayer and it worked as intended. Only on
multiplayer did it not work, only realized after I had gone through
multiple carob nut pairs thinking i was doing it wrong.

**Comment by xJon** [comment]
I managed to breed them on multiplayer. Did you make sure you are breeding a female and a male?

**Comment by NopeNopeNope2** [comment]
Yes

**Comment by xJon** [comment]
Do you have any other steps to reproduce the issue? I have tried to breed them on a server and got a baby chocobo.

**Comment by NopeNopeNope2** [comment]
I'm assuming that there's been patches since I played but I have not played
since then as I got busy, but I can try to get on later and see if it's
still happening, ill let you know.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
