### ISSUE TITLE
Final Plateau on Twilight Forest crashes the server

### ISSUE THREAD

**Issue by ImportFlask** [xJon/Hexxit-II#245]
### Was this bug reported before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/j4PjluV

### Please describe the issue you are experiencing

Hello. A friend of mine and I decided to play some Technic Hexxit II (ver. 1.5.1) a while ago. Everything was going smoothly until we reached the Final Plateau within Twilight Forest's dimension. The game server started crashing the moment we got close to the center of the castle, and now it crashes instantly whenever we try to join the server, making it unplayable. Singleplayer, on the other hand, works just fine.

**Comment by xJon** [comment]
I apologise about this issue, it is a duplicate of https://github.com/xJon/Hexxit-II/issues/223.
For now you can simply update the mod to this version - https://github.com/Elite-Modding-Team/TwilightForest-Hexxit/releases/tag/3.11.1023, to resolve the issue.
I expect a new Hexxit update to come out in the next 1-2 months which resolves this, as well as add a bunch of new content!

**Comment by ImportFlask** [comment]
Thanks for a quick heads up. Haven't noticed that issue and opened a duplicate one, silly me. Will update to the provided version.
