### ISSUE TITLE
Adding Glowstone Dust to Potion of Healing creates Potion of Corrosion instead of Potion of Healing 2

### ISSUE THREAD

**Issue by TayMac95** [xJon/Hexxit-II#247]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

I am trying to make potion of healing II so I am adding glowstone to the potion of healing but it is creating potion of corrosion instead.

**Comment by xJon** [comment]
Hi! Thank you for the report. I believe this is a duplicate of https://github.com/xJon/Hexxit-II/issues/211, and I hope the new big Hexxit update will be ready soon!
