### ISSUE TITLE
Technic launcher refuses to download the modpack alltogether

### ISSUE THREAD

**Issue by ImaQtSherlok** [xJon/Hexxit-II#25]
**Basic details**
- **Are you using Java 8, 64-bit?**: no / yes
- **Did you add any additional mods**: yes (detail) / no
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Help needed**

A clear description of what help is needed.
![249448362_453884212735570_200793207415699081_n](https://user-images.githubusercontent.com/93364613/139376224-05b530c4-cde6-4afd-9b5e-b4a6e8a72790.png)
Don't know how to fix this issue. Idk if it's with technic launcher or the modpack itself?

**Comment by xJon** [comment]
Hi! For modpack download / launcher issues make sure to head over to Technic's `#tech-help` Discord channel and upload your log there: https://discord.gg/KJjbBFSma5
