### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by TeKett** [xJon/Hexxit-II#27]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**
RTX 2070 super
i9 9900k
32gb ram 3200MHz

Pack runs abysmally. There is no difference between 2 or 32 render distance, fps is around 60-80. It is stuttering every second, and after a few minutes it has slowly started to stutter more.
![Screenshot_34](https://user-images.githubusercontent.com/64377023/139465999-c3476dea-d283-4a98-9a96-e1279ee52980.png)

**Comment by xJon** [comment]
Hi, can you try turning off Dynamic Lights? (Press `L`).

**Comment by TeKett** [comment]
Turning it off solved most of the spikes, it still ran pretty bad so i did some java argument stuff and now run perfectly fine with (but i dont actually know what the last 2 arguments does):
`-Xmx4G -Xms4G -Xmn2g -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:G1HeapRegionSize=32M -XX:+UseNUMA -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true`

**Comment by clienthax** [comment]
Prob just GC spikes because you are running on 4gb..

**Comment by xJon** [comment]
4GB of RAM should be enough, but I'm not sure if the Java arguments would be recommended.
Optifine is a great addition for extra performance!
