### ISSUE TITLE
Is Corrupted supposed to not work for Tinkers?

### ISSUE THREAD

**Issue by bidoblob** [xJon/Hexxit-II#28]
As implied by the title, corrupted can't be used to create any tinkers construct items, despite the book implying that ability. Interestingly enough, you can melt it down, but you can't even use the to make an ingot again. 

Tried with the dust, ingot, smelting, and not.

**Comment by xJon** [comment]
That's a good question, it might be unfinished by the mod (Soul Shards Respawn) as it is no longer in active development.
