### ISSUE TITLE
Can't download file

### ISSUE THREAD

**Issue by dod0lp** [xJon/Hexxit-II#29]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no

**Help needed**

When I want to download this modpack this error pops up:
![image](https://user-images.githubusercontent.com/56415227/139531598-c954fe8f-da95-4d4f-bafb-765e94815c82.png)

**Comment by xJon** [comment]
Hi! For modpack download / launcher issues make sure to head over to Technic's `#tech-help` Discord channel and upload your log there: https://discord.gg/KJjbBFSma5
