### ISSUE TITLE
download problem

### ISSUE THREAD

**Issue by ademraptor** [xJon/Hexxit-II#30]
hi, i know this problem happened many times, but does someone have a solution for this error ?
when im trying to download hexxit 2 it says :  Failed to download https://libraries.minecraft.net/.....

need help, thank you

**Comment by xJon** [comment]
Hi! For modpack download / launcher issues make sure to head over to Technic's `#tech-help` Discord channel and upload your log there: https://discord.gg/KJjbBFSma5
