### ISSUE TITLE
Server file

### ISSUE THREAD

**Issue by zz12336** [xJon/Hexxit-II#31]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**:  not applicable

**Help needed**

A clear description of what help is needed.
the server file does not work

**Comment by xJon** [comment]
I can download it, what exactly doesn't work for you?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
