### ISSUE TITLE
Mo' Creatures' CustomMobSpawner incompatible with modded biomes causing missing spawns

### ISSUE THREAD

**Issue by JohnnyMasuku** [xJon/Hexxit-II#32]
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes, just Optifine
- **Crash/latest log link (if applicable)**: not applicable

**Description**
3 things.

1 - Apparently, it is not spawning any type of Mobs in non-vanilla biomes (as you can see in the minimap screenshot). In vanilla biomes it is spawning normal, but in any non-vanilla biome it is like this.

![image](https://user-images.githubusercontent.com/93458888/139565431-e4f4ff1e-a02d-4113-b19b-bd47f55d835f.png)
<details>
2 - Some fish from Mo'Creatures are appearing with the sheep icon on the minimap (as you can see in the minimap screenshot), but that doesn't hurt at all. so just for the record.

![image](https://user-images.githubusercontent.com/93458888/139565431-e4f4ff1e-a02d-4113-b19b-bd47f55d835f.png)

3 - With Optfine installed, when I change the Mipmap level this happens (see screenshot), but as Optifine was an addition of mine, I have nothing to complain about, so just to be registered for possible future Issues.

![image](https://user-images.githubusercontent.com/93458888/139566058-144489c4-2d2b-4903-834c-210080d6db63.png)
</details>
And that's it. if you can help me mainly with the spawns I would be very grateful. Thanks for your attention, your modpack is very good at all :D (and sorry for some gramatical errors, im using google translate :v)

**Comment by xJon** [comment]
Hi, thanks for the report!
Regarding 1, it might be an issue with Mo' Creatures' CustomMobSpawner and I will investigate.
Regarding 2, unfortunately there's not much we can do with VoxelMap's head to entity support.
Regarding 3, mipmap levels are not supposed to be adjusted in modded Minecraft and are disabled by default.

**Comment by JohnnyMasuku** [comment]
Ok, thanks, I'm waiting, this bug in spawning is really quite annoying!

**Comment by xJon** [comment]
From my testing it seems that Mo' Creatures' CustomMobSpawner is incompatible with Project: Vibrant Journeys and Traverse Reforged's biomes, as it only has built-in support for these mods' biomes which appear in this part of the code: https://github.com/DrZhark/mocreaturesdev/blob/1.12.1/src/main/java/drzhark/customspawner/environment/EnvironmentSettings.java#L808
We will try to see how we can add support as soon as possible.

**Comment by clienthax** [comment]
👀

**Comment by xJon** [comment]
This is fixed in `1.1.0` thanks to @clienthax!
