### ISSUE TITLE
Reliquary experience inconsistency bug

### ISSUE THREAD

**Issue by RobertoNDF** [xJon/Hexxit-II#33]
**Basic details**: The experience acquired by reliquary mod items shows inconsistencies.
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**:
I was playing Hexxit II and finally got my hands on an infernal tear from the reliquary mod. I started farming Xp by mining netherrack and my levels were going up. I then went out of the nether and for some reason all my Xp was gone. I then killed a passive mob and noticed my Xp was back. I then went to the advanced enchantment table, from enchanting plus mod, to get mending on my chestplate. My levels were consumed and the chestplate had mending on it, but as soon as it entered directly on the chest slot in my inventory the enchantment disapeared. This didnt happen with any enchantment before i got the infernal tear, but since i got the infernal tear the Xp just vanishes every time i change dimensions or try to enchant something, and then the levels get back to normal as soon as i get more Xp. Im calling it inconsistency because sometimes the enchanting works and sometimes it doesnt. I have to keep getting a bit more of xp to try it a lot of times. The bug that makes the experience bar seem like it has no xp at all is consistent within every single time i go to the nether and back to the overworld. Didnt try the end yet to see if the bug happens there too. It really got me worryed the first time and its really anoying to keep reseting the bar by gaining xp.

**Comment by xJon** [comment]
Can you please provide steps to reproduce this issue? Thank you!

**Comment by xJon** [comment]
This should be fixed now in the latest version of the modpack with the inclusion of the [Fix Experience Bug](https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug/files/3372374) mod :)
