### ISSUE TITLE
Server error(crash report) but without affecting the performance

### ISSUE THREAD

**Issue by TomasGnG** [xJon/Hexxit-II#34]
The error:
https://www.toptal.com/developers/hastebin/fezoluyojo.rb

**Comment by xJon** [comment]
Can you attach a full game log? It will be useful for the developer's debugging. Thank you!

**Comment by TomasGnG** [comment]
Here is the file its kinda big(19mb)
[Download](https://workupload.com/file/cEkaRcetTZ9)

**Comment by xJon** [comment]
Thank you, I've forwarded it to the mod author. For now I will close this as it's a duplicate of https://github.com/xJon/Hexxit-II/issues/12 but your report is very helpful!
