### ISSUE TITLE
Detailed Changelog

### ISSUE THREAD

**Issue by UeberallGebannt** [xJon/Hexxit-II#35]
Is there a detailed changelog for the modpack (containing all files that changed) so that I can manually update my server?

**Comment by xJon** [comment]
You could use an app such as Lukas' [Changelogger](https://mc-changelogger.web.app/).

**Comment by UeberallGebannt** [comment]
![grafik](https://user-images.githubusercontent.com/50475262/139699072-c62167b2-8fe7-4bf5-b535-76c2162bdca3.png)
This however does not include which configs have been changed if I'm correct.

**Comment by xJon** [comment]
That's true, for that you could use a comparison tool but the best solution would just be to replace the old configs folder with the new one.
If you made any config changes you'd like to keep between updates you can keep track of them and reapply them yourself

**Comment by UeberallGebannt** [comment]
Wouldn't it be easier then to just give the changelogs to the user? For example just address each file that changed in the log explicitly? 

Doing like you said would be a solution tho.

**Comment by xJon** [comment]
Not sure which format that would take place, might make changelogs very cumbersome.

**Comment by clienthax** [comment]
@xJon Just do the configs on a github repo, push a new tag each update, simple.
