### ISSUE TITLE
Dropped Heart and Dropped Emerald Shards

### ISSUE THREAD

**Issue by Finnexis** [xJon/Hexxit-II#36]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Dropped Hearts and Emerald Shards get collected by hoppers and they are not stackable, please fix

**Comment by xJon** [comment]
Emerald shards should stack, but the hearts do not as they are not supposed to get into the player's inventory.
We will look into options of making them not interfere with hoppers.

**Comment by xJon** [comment]
@phantamanta44 has implemented new changes to address the issues you were having, they will be included in the next version of the modpack :)

**Comment by xJon** [comment]
Drops will stack in `1.1.0`!
