### ISSUE TITLE
Sea Shells obtaining method.

### ISSUE THREAD

**Issue by lordgrunt** [xJon/Hexxit-II#37]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes , only Armory Expansion (armoryexpansion-1.4.2.jar)
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Describe the issue**

Bug or no, its a bit inconsistent that in order to obtain the drop, prismarine, from those, you have to shift-right click them while they have in their tooltip (waila-like description) that pickaxe is a proper tool to harvest it. doing so with said tool, even with silk touch, gives nothing.

A clear description of what the issue is.

**Comment by xJon** [comment]
From https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/issues/22#issuecomment-421639786:

> You have to right click it while sneaking to pick it up.
