### ISSUE TITLE
TombManyGraves

### ISSUE THREAD

**Issue by Staqur** [xJon/Hexxit-II#4]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:   no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**
Player died and when accessing his grave his inventory bugged out and kicked him, when he tried to rejoin server crashed. He also got this error https://gyazo.com/439a346709155d477c6fc936571a4ae3

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
