### ISSUE TITLE
Falling stars crashes the game

### ISSUE THREAD

**Issue by ZexyGamerah** [xJon/Hexxit-II#42]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: I don't know how to do that

**Describe the issue**

I was gaming on hexxit 2 when in my hot bar was the message stars are falling tonight or something like that later I saw something sparkly so I walked into it and it crashed my game, even after I restarted it and got back in my world it again crashed and I cant go in my world anymore. I don't wanna restart all over...

**Comment by clienthax** [comment]
crash report?

**Comment by Magicmason1000** [comment]
If you have Windows, in the search bar on the bottom left, type "run" and hit enter. A box should come up that says "Type the name of the program" and then enter this in: C:\Programs\Technic\modpacks\hexxit-ii\reports
That should bring you to the crash reports where you can copy and paste them into this.

**Comment by ZexyGamerah** [comment]
Hithis is the only thing I could find which is a WinRAR thing. Sent from Mail for Windows From: Magicmason1000Sent: Saturday, 6 November 2021 22:37To: xJon/Hexxit-IICc: ZexyGamerah; AuthorSubject: Re: [xJon/Hexxit-II] Falling stars crashes the game (Issue #42) If you have Windows, in the search bar on the bottom left, type "run" and hit enter. A box should come up that says "Type the name of the program" and then enter this in: C:\Programs\Technic\modpacks\hexxit-ii\reportsThat should bring you to the crash reports where you can copy and paste them into this.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
