### ISSUE TITLE
World crashes on start?

### ISSUE THREAD

**Issue by TheGodlyChair** [xJon/Hexxit-II#43]
Just playing my world and then it just suddenly crashed. I tried to get back into the world but the game crashed again saying that the problem was the Chocolate Quest repoured mod. I am using Java 8, 64-bit and I have not added any other mods.

[crash-2021-11-06_14.23.29-server.txt](https://github.com/xJon/Hexxit-II/files/7491130/crash-2021-11-06_14.23.29-server.txt)

**Comment by clienthax** [comment]
Corrupted file of CQR, something in %world%/data/CQR/protected_regions

**Comment by TheGodlyChair** [comment]
> Corrupted file of CQR, something in %world%/data/CQR/protected_regions

So can I do something about it or is my world gone?

**Comment by xJon** [comment]
Did you try rolling back to a world backup? You could also try to reset the file @clienthax referred to.

**Comment by TheGodlyChair** [comment]
> Did you try rolling back to a world backup? You could also try to reset the file @clienthax referred to.

Thank you for the help but, the most recent backup was yesterday so if I can get the world back as it is that would be great and how would I go about resetting the file?

**Comment by xJon** [comment]
The file would be located in the path @clienthax showed, where `%world%` would be your world save folder.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
