### ISSUE TITLE
Unable to craft big backpack

### ISSUE THREAD

**Issue by starlynn1978** [xJon/Hexxit-II#44]
**Basic details**
- **Are you using Java 8, 64-bit?**: no / yes   yes 
- **Did you add any additional mods**: yes (detail) / no    no
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Describe the issue**
After crafting each piece to make the big backpack and placing them in order in the crafting table  The big backpack will not craft.  I even tried relogging into the game and nothing worked.
A clear description of what the issue is.

**Comment by xJon** [comment]
Can you attach a screenshot?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
