### ISSUE TITLE
Type on Title Screen?

### ISSUE THREAD

**Issue by Magicmason1000** [xJon/Hexxit-II#45]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**
On the title screen, I think there is a typo in the Discord links. I'm not sure if it is supposed to say "Jon Discord" or if that is a typo. If it's something else, I suggest making it clearer on what that means. Possibly Hexxit Discord?

**Comment by xJon** [comment]
It's supposed to say `Jon Discord` as to refer to my Discord server, in order to ask me questions about the modpack.

**Comment by Sandshrew6** [comment]
Maybe make it say "Jon's discord", so it's more clear what it is and looks less like a typo of "join discord"?

**Comment by xJon** [comment]
That was changed in the latest version :)
