### ISSUE TITLE
Dimensional doors not working properly

### ISSUE THREAD

**Issue by RobertoNDF** [xJon/Hexxit-II#47]
**Basic details** Dimensional quartz door does not work if you leave the game inside of the pocket dimension and then try to get out of the pocket dimension back to the overworld.
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**
 
I was playing in my long-term-planned world in Hexxit and just created a pocket dimension with quartz doors, which i was planning to turn into a portable base, not needing to have any physical base and being able to explore further in less time. I had at least 40 of those fabric black strings, meaning i could do already 20 doors to access my base from far away from the original door. The problem is: I had to log out of the game bc it was late and I needed to sleep. When I enter in the game again I finish working in my portable base design I try to go back to my overworld base and it doesnt work. Im stuck in the pocket dimension and the message shown is attached
![Quartz dimension bug proof](https://user-images.githubusercontent.com/93459019/140627922-f33457e9-7d92-4d56-8974-5c136b7aa31b.png)
.

**Comment by xJon** [comment]
For now I'd suggest you to rollback to a backup, but thank you for reporting this & we will look into the issue!

**Comment by xJon** [comment]
Can you test whether this issue is still present with the latest version of the modpack? (`1.4.0`)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the requested info :)
