### ISSUE TITLE
Lost Books formatting errors

### ISSUE THREAD

**Issue by Magicmason1000** [xJon/Hexxit-II#48]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**
There is a text error in one of the books. I got this from a battle tower, and the text has some code parsed incorrectly. The book is called "Bad Jokes Compilation."
![Screenshot 2021-11-06 225756](https://user-images.githubusercontent.com/46111269/140631801-c9e86d0e-e0f0-4f41-a191-9cfa202f7c39.png)

**Comment by xJon** [comment]
Hi! Thank you for reporting this, it is most likely intentional although there's not much we can do about it nevertheless

**Comment by xJon** [comment]
Unless someone who better understands this issue can help, there's nothing else I can do at the moment.
