### ISSUE TITLE
Hexxit 2 Bukkitgui not working properly

### ISSUE THREAD

**Issue by Shizurake** [xJon/Hexxit-II#49]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- 
Hello, I downloaded Hexxit 2 server, then via bukkitgui I started it and with mahachi me and my friend started playing, but the game is not working as it should. After we first connect we should get 2 books ( Hexxit 2 and Aka... something ), but we didn´te get any. Also when I click Baubles in my inventory, nothing happens. We can´t craft some of the items ( because of mods? ) like crafting station, tool forge, iron strongs and I don´t know how many more. Could someone help me how to play it normally with all mods etc working? I just want to play with my friend, but if we cannot craft items and use this mod fully, then it´s bad. Thank you

**Help needed**

**Comment by xJon** [comment]
This sounds like you are not launching your server using Forge. Make sure to use the launch server script included in the server package.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
