### ISSUE TITLE
Tame Limit on SinglePlayer

### ISSUE THREAD

**Issue by sodabutty** [xJon/Hexxit-II#51]
Hi, there's a tame limit on my singleplayer game which is confusing cause its singleplayer, is there a way I can turn it off? I'm playing this mod pack for the fun and animals :( not as fun if I cant have as many animals tamed and I want

**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**

**Comment by xJon** [comment]
Hi! Pretty sure I saw your post over Reddit as well :)
> You can manually edit this limit through the modpack's installation folder -> config -> MoCreatures -> MoCSettings.cfg -> line 115

We will change this in singleplayer in the next update :)

**Comment by xJon** [comment]
This was changed in the `1.2.0` update!
