### ISSUE TITLE
Game will not launch 

### ISSUE THREAD

**Issue by jslider12** [xJon/Hexxit-II#52]
The technic launcher had downloaded the modpack but whenever i click launch it pop up a window for a fraction of a second and then nothing happens. everything is up to date and i am allocating 10gb of ram. there are no crash logs or anything else for me to add 

system specs
GPU: RTX 2080 super
CPU:I7-10700k
Ram: 32GB

**Comment by xJon** [comment]
Hi! For modpack download / launcher issues make sure to head over to Technic's `#tech-help` Discord channel and upload your log there: https://discord.gg/KJjbBFSma5
