### ISSUE TITLE
Purple Slimesling

### ISSUE THREAD

**Issue by DragonARandom** [xJon/Hexxit-II#54]
Unsure if this is a mod pack issue or just a mod issue, but I attempted to use a purple slimesling that I had obtained from one of the underground dungeons and it crashed as soon as I should be slung.

**Comment by xJon** [comment]
Hi, can you please attach a crash report?

**Comment by DragonARandom** [comment]
Where would i find it?

**Comment by xJon** [comment]
`\.technic\modpacks\hexxit-ii\crash-reports\`.

**Comment by DragonARandom** [comment]
[crash-2021-11-08_20.04.28-client.txt](https://github.com/xJon/Hexxit-II/files/7506649/crash-2021-11-08_20.04.28-client.txt)

**Comment by DragonARandom** [comment]
I did not modify the pack in my way, and when i try to use the purple slimesling again, it lags with about a 50% chance of a crash, I have tried the other three colors and they did not produce any lag outside of terrain generation

**Comment by xJon** [comment]
This seems to be a duplicate of https://github.com/SlimeKnights/TinkersConstruct/issues/2470, https://github.com/SlimeKnights/TinkersConstruct/issues/3551. Probably a rare Tinkers bug which is not easy to reproduce, I was not able to myself. There's not much we can do unfortunately but thank you for reporting this nonetheless!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
