### ISSUE TITLE
Silver ore missing

### ISSUE THREAD

**Issue by neobigd** [xJon/Hexxit-II#55]
**Basic details**
- **Are you using Java 8, 64-bit?**:  **yes**
- **Did you add any additional mods**:  **no**
- **Crash/latest log link (if applicable)**: **not applicable**

Noticed the mod Iron Chest uses silver ingots to get the diamond chest, but there dont seem to be any ore or ingot blocks in game, nor in looking in JEI

**Comment by ItachiSuwoo** [comment]
I am having same problem. No electrum or sliver ore/ignot. Thermal Foundation bug?

**Comment by xJon** [comment]
Hi, they have been disabled in the modpack.
