### ISSUE TITLE
saddle bags

### ISSUE THREAD

**Issue by BloodfART** [xJon/Hexxit-II#56]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: [crash-2021-11-09_18.50.36-client.txt](https://github.com/xJon/Hexxit-II/files/7508744/crash-2021-11-09_18.50.36-client.txt)

**Describe the issue**

Shift clicking items into Chocobo saddle bags crashes the game. I can click and drag the items in without it crashing only shift clicking crashes it.

**Comment by xJon** [comment]
Thank you for the report! I've forwarded the details to the mod author

**Comment by xJon** [comment]
This is fixed in the latest update!
