### ISSUE TITLE
Cant craft backpacks

### ISSUE THREAD

**Issue by Kazuoh123** [xJon/Hexxit-II#57]
Are you using Java 8, 64-bit?: yes
Did you add any additional mods: no
Crash/latest log link. don't know how, sorry.

Describe the issue

Whilst having all I need to make the middle backpack and the big backpack. I am not able to craft them in either a crafting table or a tinkers crafting station

**Comment by Longshot133** [comment]
are they the same tier?
different tier levels cant be combine

**Comment by Kazuoh123** [comment]
I'm just crafting them normally with the frames not upgrading them

**Comment by xJon** [comment]
Can you please attach a screenshot or a GIF of your attempt?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.

**Comment by ZeroSeconds020** [comment]
I seem to have sort of a same issue, I can't craft the Big Backpack even tho all the Backpack pieces are placed correctly.

**Comment by xJon** [comment]
@ZeroSeconds020 Are they all of the same tier?

**Comment by ZeroSeconds020** [comment]
Yea problem fixed. I accidentally made 1 piece of regular leather and the 2 others of tanned leather, thank you for your help tho :)
