### ISSUE TITLE
Why is my tinkers tools cap at level adept?

### ISSUE THREAD

**Issue by YeYethePooh** [xJon/Hexxit-II#58]
I thought there are no level caps in this. But all my tools only goes up to adept then the "xp ---/---" disappear entirely
![shuriken](https://user-images.githubusercontent.com/94092285/141227609-9ca8953b-8844-41d6-aaa0-110c9805fe99.png)
.

**Comment by xJon** [comment]
It is capped for game-balance reasons.

**Comment by YeYethePooh** [comment]
Ooooo,
 Ok thank you for the verification!
