### ISSUE TITLE
Error downloading a file / Can't download the pack

### ISSUE THREAD

**Issue by ItsADum** [xJon/Hexxit-II#59]
**Basic details**
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: No
- **Crash/latest log link (if applicable)**: Not Applicable

**Describe the issue**

When I attempted to download the modpack I was stopped by an error:
![hexxit 2 error](https://user-images.githubusercontent.com/94141349/141363800-b37f4e9d-ca9b-4d29-854e-818dd9d0d728.png)

**Comment by xJon** [comment]
Hi! For modpack download / launcher issues make sure to head over to Technic's `#tech-help` Discord channel and upload your log there: https://discord.gg/KJjbBFSma5
