### ISSUE TITLE
it seems like there are some things missing from tinkers' construct, for example Mighty Smelting

### ISSUE THREAD

**Issue by redrevo117** [xJon/Hexxit-II#60]
I was just wondering if the Book Mighty Smelting is just not in this version or if its a bug, 

It has been quite some time since ive messed with Tinkers' Construct and those books are quite useful when figuring things out

also the text on some of the pages of materials and you go off the pages

**Comment by xJon** [comment]
In 1.12.2 Tinkers only adds one book with all of the information :)
You can find it in the Akashic Tome book you spawn with!
