### ISSUE TITLE
Treecapitator and giant beanstalks from Twilight Forest

### ISSUE THREAD

**Issue by lordgrunt** [xJon/Hexxit-II#61]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: yes (armor expansion)
- **Crash/latest log link (if applicable)**:  not applicable

**Describe the issue**
Attempt to whack at any of the giant beanstalks blocks with any kind of axe, be it a bottom one or higher ones, freezes the game for (in my case) a minute or so. after that game resumes normally.

A clear description of what the issue is.

**Comment by xJon** [comment]
This might be harder to fix due to https://github.com/bspkrs/Treecapitator/issues/47.

**Comment by xJon** [comment]
This is no longer an issue in the `1.2.0` update as we replaced Treecapitator!
