### ISSUE TITLE
I keep getting a crash report about DrZhark's Customspawners

### ISSUE THREAD

**Issue by Cheesee64** [xJon/Hexxit-II#62]
**Basic details**
- **Are you using Java 8, 64-bit?**:  _yes_
- **Did you add any additional mods**:  _no_
- **Crash/latest log link (if applicable)**:  _not applicable_

**Help needed**

I received this crash report about the DrZhark's Customspawners, I tried to get the link for it because it said to and it keeps saying that it failed. it wont let me play on any of my worlds. I just want to figure out how to play on my worlds again and hope it doesn't delete anything. I'm not very tech smart so any help is welcomed!! Thank you, if I need to add anymore information ill try my best to get it for anyone!!

**Comment by xJon** [comment]
Thank you for the report! First of all, you could try to use a world backup. But it would be really helpful if you can attach here a crash report! You can find it in the modpack's installation folder under `crash-reports` :)

**Comment by Cheesee64** [comment]
i hope i did it right, https://paste.ubuntu.com/p/TscTDdvKcm/ this should be the crash report

**Comment by xJon** [comment]
Can you try to go to that path (`C:/Users/drake/AppData/Roaming/.technic/modpacks/hexxit-ii/config/CustomSpawner/overworld/Creatures/`) and reset (delete) `BLAY09.cfg` (after backing it up)?

**Comment by Cheesee64** [comment]
sorry for the late response i got busy, BUTTT may i ask how to back it up i don't want to mess anything up, sorry T_T

**Comment by Cheesee64** [comment]
I deleted the BLAY09.cfg and i tried opening a worlds again and it didnt world :(

**Comment by Cheesee64** [comment]
https://paste.ubuntu.com/p/mJtGzsgry3/ this is my newest crash report

**Comment by xJon** [comment]
Can you take a screenshot of the files inside your `hexxit-ii/config/CustomSpawner/overworld/Creatures/` folder?

**Comment by Cheesee64** [comment]
https://prnt.sc/1zkd268 this is the screenshot

**Comment by xJon** [comment]
Did you try reinstalling the modpack through the launcher?
> `Modpack Options` -> `Reinstall Pack`

**Comment by Cheesee64** [comment]
not yet but ill give it a try

**Comment by Cheesee64** [comment]
OHH it worked, i didnt know itd be so easy thank you so much!! thank youuuuuuu!!!

**Comment by xJon** [comment]
That's wonderful :)
