### ISSUE TITLE
Can't enchant Meteor equipment when full durability.

### ISSUE THREAD

**Issue by Tishbyte** [xJon/Hexxit-II#64]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

When trying to enchant the Meteor equipment (Nyx mod), it won't let me place it inside the Advanced Enchantment Table when it's at full durability.
I ran into this because I added mending on and was no longer able to enchant my gear. Was able to stumble upon the solution of using a cactus/using my tools to enchant once again.

**Comment by xJon** [comment]
It was disabled recently (see https://github.com/xJon/Hexxit-II/issues/41) but we might reenable it due to popular demand.
