### ISSUE TITLE
Increase slime spawn rates

### ISSUE THREAD

**Issue by Tishbyte** [xJon/Hexxit-II#65]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**
Default Minecraft slimes aren't spawning in either slime chunks or swamplands. Ran into this issue as we need them to drop slim pearls for Reliquary. Also using Tinkers Construct tools with the slimy modifier doesn't spawn slime either.

**Comment by xJon** [comment]
Hi, we'll increase the spawn rates of them in the next update, thanks!
![image](https://user-images.githubusercontent.com/8945347/143895793-7954660c-3ae4-4e8b-8aab-b61b14cc9204.png)

**Comment by xJon** [comment]
This was changed in the `1.2.0` update!
