### ISSUE TITLE
Blue Slime Scythe with Mending Moss modifier doesn't regain durability

### ISSUE THREAD

**Issue by Tishbyte** [xJon/Hexxit-II#66]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**
The Blue Slime Scythe (Tinkers Construct) with the mending moss modifier doesn't regain durability.

**Comment by xJon** [comment]
Are you collecting XP with it?

**Comment by Tishbyte** [comment]
Yes.

**Comment by xJon** [comment]
You need to make sure you are holding it whilst collecting XP:
![Gif](https://user-images.githubusercontent.com/8945347/144731836-0bca2619-5d27-4051-b035-da822cbf5b8c.gif)
