### ISSUE TITLE
Huge TPS loss on river generation

### ISSUE THREAD

**Issue by zediious** [xJon/Hexxit-II#67]
**Basic details**
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: No
- **Crash/latest log link (if applicable)**: Relevant river generation log followed by /forge tps at the bottom of log [latest.log](https://gist.githubusercontent.com/zediious/8127b6e556aa29a1fe1a32a67049713a/raw/2d786a638bd4e9af6deb14c3f82856a57ae53928/latest.log)

**Describe the issue**

Around 5 minutes after world generation, a river seems to generate (per the log). I noticed the TPS drop right away due a Bounty Board not opening. After /forge tps resolved, mean tick time was 1639.427. The lag stopped presumably after the river finished generating, but I'm not sure if this related to how the rivers are generating, etc.

**Comment by xJon** [comment]
Unfortunately there's not much we can do about laggy world generation in 1.12.2. We have [ChunkGenLimiter](https://www.curseforge.com/minecraft/mc-mods/chunkgenlimited) but it can only do so much.
