### ISSUE TITLE
Capsules

### ISSUE THREAD

**Issue by 5parkPlug** [xJon/Hexxit-II#68]
Would it be possible to add the capsules mod. These were in Hexxit as part of the Better Dungeons mod but they are now a standalone mod

**Comment by xJon** [comment]
Hi, just to confirm, are you referring to [this](https://www.curseforge.com/minecraft/mc-mods/capsule) mod?

**Comment by 5parkPlug** [comment]
Yep – I think that’s the one.

 

In the original hexxit they allowed people to have a mobile base that they could take when they explored (good for mobile mob spawners too!)

**Comment by 5parkPlug** [comment]
Just to confirm that is the correct mod. Chocolate Quest link to it in their FAQs...

"_Will Capsule Stations be making a return?
No, Capsule Stations are now their own mod made by Lythom, you can find it **here**._"

**Comment by xJon** [comment]
This was added in the `1.2.0` update, thank you for the suggestion :)
