### ISSUE TITLE
Issue on Hexxit 2 Server which causes tower bosses to not act as they should.

### ISSUE THREAD

**Issue by xxeonUK** [xJon/Hexxit-II#69]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes i think so im using java version "1.8.0_291" Java(TM) SE Runtime Environment (build 1.8.0_291-b10) Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**:  not applicable

**Describe the issue**

When reaching the top of the tower and the boss spawns, the boss glitches out and does exactly what is shown in the google drive link video.

The boss does seem to be able to hurt us on other levels. Its almost as if hes invisible.

The video describes the issue best.

Thanks in advance!

LINK - https://youtu.be/sUYGxdj68Do

**Comment by L0r3nz2003** [comment]
I have the same issue, is there any workaround?

**Comment by xxeonUK** [comment]
[I](https://github.com/xJon/Hexxit-II/issues/46)

see this issue thread. Jon has mentioned it to the mod owner but he said he doesnt support 1.12.2 so he would not be investigating

Currently no fix or workaround.

**Comment by xJon** [comment]
Hi! I'm closing this as it's a duplicate for https://github.com/xJon/Hexxit-II/issues/46, but thank you for the additional information! Let's continue this over the other issue thread.
