### ISSUE TITLE
Clicking on the Issue Tracker button in the book doesn't work on Linux

### ISSUE THREAD

**Issue by bidoblob** [xJon/Hexxit-II#7]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: yes, optifine
- **Crash/latest log link (if applicable)**: https://pastebin.com/QMM6zeeG
Couldn't paste in the entirety of the log, so only the relevant part was included. Tried restarting to make it as short as possible but that wasn't enough. I *think* I was actually able to drop the entire log into here, however. 

**Describe the issue**
Clicking on the Issue Tracker button in the Hexxit book causes nothing to happen. Luckily I could find the link in the Technic Discord, but otherwise I would've had a hard time finding this. 

[techniclauncher_2021-10-24.log](https://github.com/xJon/Hexxit-II/files/7403950/techniclauncher_2021-10-24.log)

**Comment by Pyker** [comment]
This is a Linux Java problem tbh, Minecraft will have the same problems

**Comment by xJon** [comment]
Will get fixed it in the next modpack update thanks to @asiekierka and their [FoamFix update](https://www.curseforge.com/minecraft/mc-mods/foamfix-optimization-mod/files/3973967) :)

**Comment by xJon** [comment]
Should be fixed in `1.4.2`!
