### ISSUE TITLE
Barked Logs

### ISSUE THREAD

**Issue by LunaSapphic** [xJon/Hexxit-II#70]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Using the _Debark_ mod, you are able to shave off the bark on logs. Using silk touch on these debarked logs, they all turn into debarked oak logs, regardless of type.

**Comment by xJon** [comment]
Seems to be a bug with the mod. I've forwarded it to the mod author, thank you!

**Comment by xJon** [comment]
As it seems Debark is no longer in active development, I'll close this issue. Thank you nevertheless for the bug report!

**Comment by asiekierka** [comment]
Sorry, turned this `wontfix` into a `canfix`

**Comment by xJon** [comment]
Will include @asiekierka's fixed version in the next modpack update :)

**Comment by xJon** [comment]
Should be fixed in `1.4.2`!
