### ISSUE TITLE
Fastbench Crash issue

### ISSUE THREAD

**Issue by Gman568** [xJon/Hexxit-II#72]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: link to log 

**Help needed**

A clear description of what help is needed.

I was playing as normal and crafting Purple dyes, when suddenly a second later my game crashed and i couldn't reopen my world.
My hard rive had disconnected but i am unsure if it has any relevance because it has happened before with no previous issue. When i tried to reenter my world, it gave "FastWorkbench" the fault for the crash. I tried to remove the mod and install an earlier version, but i didnt help. I also tried to reinstate a previous backup but it also said that it was corrupted. If someone could help me it would be appreciated :)

[Crash Report, FastBench.txt](https://github.com/xJon/Hexxit-II/files/7588737/Crash.Report.FastBench.txt)

**Comment by xJon** [comment]
Exiting Minecraft without saving usually corrupts worlds unfortunately. Are you unable to use any of the backups?

**Comment by Gman568** [comment]
My earliest backups didn't work because when I tried to reinstate it it was
corrupted, so I had to use an older backup from the previous day. But the
issue is gone now luckily.

**Comment by xJon** [comment]
That's great news, glad you found a solution at the end!
