### ISSUE TITLE
Increase ocelot spawn rates

### ISSUE THREAD

**Issue by Bak3rman** [xJon/Hexxit-II#73]
**Basic details** I'm in the jingle but no ocelots are spawning
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Describe the issue**

A clear description of what the issue is.

I have spent many day's and nights roaming the jungle but have found no ocelotes

**Comment by xJon** [comment]
Hi, we will increase the spawn rates of them in the next update, thanks!
![image](https://user-images.githubusercontent.com/8945347/143894316-b628f118-afd6-4364-8c9c-d608b31f9dc1.png)

**Comment by xJon** [comment]
This was changed in the `1.2.0` update!
