### ISSUE TITLE
Scale Armor and Emperor's Chalice lead to infinite hunger point production

### ISSUE THREAD

**Issue by dragonsflame246** [xJon/Hexxit-II#74]
**Basic details**
- **Are you using Java 8, 64-bit?**: Unsure (Using Version Bundled by Launcher)
- **Did you add any additional mods**: yes (Connected Texture Mod, Better Fps, Surge, Portal Supercache, Particle culling, optifine, clumps, fast furnace, AI Improvements, Performant, Dynamic Surroundings, Sound filters, Mouse Tweaks, Ore Lib)
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**
The resistance from the Scale Armor and the ability of the Emperor's chalice to convert health to hunger points leads to infinite hunger/health as the resistance keeps the chalice from inflicting enough damage, leading to the ability to produce infinite health/hunger.

**Comment by xJon** [comment]
Funnily enough I am able to reproduce this with just a vanilla set of diamond armor with protection IV enchantment. The only config option for the Emperor's Chalice is about the saturation and not the damage applied.
Not sure if there's much we can do about this, although we do plan to nerf the scale armor's resistance.
Thank you nevertheless for reporting this!
