### ISSUE TITLE
Hexxit 2 server issue

### ISSUE THREAD

**Issue by Shawn5192** [xJon/Hexxit-II#75]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: NA

**Help needed**

A clear description of what help is needed.

hello. Im trying to start a server from my pc but whenever i launch the server i get a bunch of errors. Im not sure what im doing wrong.
![Screenshot 2021-11-27 023212](https://user-images.githubusercontent.com/95120327/143672695-3bf9f084-3cb1-4c59-ae4d-31d743246d1d.png)

**Comment by drybonesification** [comment]
Having the same issue, have tried both java 8 and openjdk on two machines error will still occur

**Comment by xJon** [comment]
> Hi, you need to make sure you have Java SE 8 64-bit installed on your computer :)
You can find it through [here](https://www.java.com/en/download/manual.jsp).
Also, if you don't need the Java Development Kit version you currently have installed, you should remove it to avoid conflicts.

**Comment by drybonesification** [comment]
Just for giggles, i confirmed the correct version of java was installed I also tried using OpenJDK and ran into the same error as above. I also check my JDK versions and uninstalled like suggested but nothing changed same error was thrown

**Comment by Shawn5192** [comment]
Ya I tried as well and still can’t seem to get it to work.

**Comment by xJon** [comment]
If you don't need the Java Development Kit version, make sure to uninstall it.
Then, make sure you have Java Standard Edition installed.

Alternatively, if you do need the JDK version installed I could guide you to change the launch script.
