### ISSUE TITLE
Bug Report [Hexxit2 modpack]

### ISSUE THREAD

**Issue by KileVA** [xJon/Hexxit-II#76]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**:  not applicable

**Describe the issue**

Item: Big Backpack is non functional. Can place in shield inventory slot, have tried in multiple instances of Hexxit 2. Items sprite is unchanged.

A clear description of what the issue is.

**Comment by xJon** [comment]
Can you not open it? How did you craft it?

**Comment by Keith-UCT** [comment]
set the backpack key if not set, then shift+backpack key to open the single slot GUI. Place the backpack in that slot. Now when you press the backpack key, the backpack opens.
