### ISSUE TITLE
Latest Hexxit II version (1.2.0) crashing on OS X due to CQR

### ISSUE THREAD

**Issue by Moon-old** [xJon/Hexxit-II#77]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: [link to log] https://pastebin.com/pd7rz22y

**Help needed**

A clear description of what help is needed.

Hi xJon, thank you for the update and everything you have done for Hexxit 2 making it such an amazing modpack! However, I'm experiencing a slight problem with launching this newest version (1.2.0). Whenever I launch the modpack, a message popped up stating that "Minecraft failed to start!". As well as, "An error during startup prevented Minecraft from starting". It would be much appreciated to get some help fixing the issue and looking forward to finding a solution soon. Thank you!

**Comment by xJon** [comment]
Thanks for the report!
This seems to be some sort of incompatibility between the latest Chocolate Quest Repoured update and OS X's OpenGL drivers.
Hopefully the CQR team can look into this, but in the meantime make sure your graphical drivers are all up to date :)

**Comment by ChillaxOwner** [comment]
Is there any alternative fix? I have many users whom cannot launch their client still.

**Comment by Moon-old** [comment]
I have been doing some testing and it seems that both Chocolate Quest Repoured and Bountiful are having trouble with the OS x's OpenGl drivers.
Crash Report: https://pastebin.com/YBLTsik8

**Comment by xJon** [comment]
We're still waiting for a CQR update, for now you should stay on `1.1.0`!

**Comment by nicholasoty** [comment]
Hi, is anyone able to confirm if the latest 1.2.1 update fixed this issue?

Thanks in advance!

**Comment by ChillaxOwner** [comment]
It has not

**Comment by xJon** [comment]
@nicholasoty I mentioned it in the `1.2.1` changelog over https://www.technicpack.net/modpack/hexxit-ii/changelog/2019166.
This is still an issue with CQR.

**Comment by xJon** [comment]
@Moon-old @thejbone @nicholasoty Can any of you try to launch [the latest version of CQR](https://www.curseforge.com/minecraft/mc-mods/cqrepoured/files/3587389) and confirm whether it is working for you or not? You can try to launch it on its own using the CurseForge launcher.

**Comment by thejbone** [comment]
@xJon I had a player with a Mac test it and it boots.

**Comment by xJon** [comment]
@thejbone That's wonderful news! And the same player could not load the previous version of the mod?

**Comment by thejbone** [comment]
> @thejbone That's wonderful news! And the same player could not load the previous version of the mod?

Yep.

**Comment by xJon** [comment]
This is now fixed in version `1.3.0`!
