### ISSUE TITLE
server help

### ISSUE THREAD

**Issue by vainrazer2** [xJon/Hexxit-II#81]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: link to log / not applicable

https://imgur.com/a/QTXts5y

**Describe the issue**

A clear description of what the issue is.

I am trying to run a server for this off my pc but when I press launchserver.bat it comes with an error
https://imgur.com/a/QTXts5y
image is shown at this link, I
don't know what is wrong or what is an issue and I would like some help
![image_2021-12-13_192501](https://user-images.githubusercontent.com/96080937/145875126-cb9bf242-7413-49ed-9cfb-e6c7d08c61f1.png)

**Comment by xJon** [comment]
> Hi, you need to make sure you have Java SE 8 64-bit installed on your computer :)
You can find it through [here](https://www.java.com/en/download/manual.jsp).
Also, if you don't need the Java Development Kit version you currently have installed, you should remove it to avoid conflicts.
