### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by neadcb** [xJon/Hexxit-II#83]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: link to log / not applicable

[hs_err_pid8168.log](https://github.com/xJon/Hexxit-II/files/7740027/hs_err_pid8168.log)

Please post game log links using a paste-tool such as https://paste.ubuntu.com or https://pastebin.com/index.
DO NOT paste the log into the issue. It will make your issue hard to read.
-->

**Describe the issue**

Attempting to chop down a tree, and the game crashes to desktop and the launcher comes back up.

Please let me know if you need additional files.

**Comment by xJon** [comment]
Hi! Can you reproduce this issue? Do you have any steps in order to reproduce it?

**Comment by neadcb** [comment]
I restart the game, go to chop down another tree and it crashes to desktop again.
I can try a uninstall / reinstall to see if that fixes the issue.


-----Original Message-----

**Comment by xJon** [comment]
That'd be great, also did you play the game for a while before it started crashing?

**Comment by neadcb** [comment]
I've played this one a few times.I started out, found a location and started building a house.  Then the game crashed.Restarted a few days later, and again, upon chopping down a tree, game crashed.Restarted right away, the logs from the felled tree were waiting for me.  Chopped down another tree and crash.Restarted a third time a few hours later.  Logs from felled tree were waiting for me and the game was stable until I quit.Started again later tonight and the game has been stable.
So, not sure what was going on.If I get another crash, I'll submit the log files.
You can downgrade this one to a "watch" or "random event" so it doesn't clog up your workload.
ThanksChris


-----Original Message-----

**Comment by xJon** [comment]
The crash you are experiencing is usually caused by memory errors, and not the modpack specifically - keep this in mind if you experience crashes in other modpacks / games, but thank you for reporting this nonetheless!

**Comment by xJon** [comment]
Closed due to inactivity. Will reopen if requested!
