### ISSUE TITLE
No loot spawning in chests on private hexxit 2 server

### ISSUE THREAD

**Issue by joedicamillo** [xJon/Hexxit-II#84]
**Basic details**
- **Are you using Java 8, 64-bit?**: no / yes
- **Did you add any additional mods**: yes (detail) / no
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Help needed**

A clear description of what help is needed.
Whenever we go into a "raid" all of the chests are empty. is there some sort of setting in the server file I can go into and change? thank you

**Comment by joedicamillo** [comment]
from my knowledge actually, it's only in those houses with the large basements

**Comment by xJon** [comment]
Hi! Can you please attach a screenshot of what you mean?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
