### ISSUE TITLE
Unsure if server is being created 

### ISSUE THREAD

**Issue by lauber1954** [xJon/Hexxit-II#86]
**Basic details**
- **I am using Java 8 update 301, 64 bit
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: not applicable

Hey!
I am trying to make a hamachi server for Hexxit 2, i am able to launch the bat file, it looks as if the prompt finishes the setup as it looks like this. 

![image](https://user-images.githubusercontent.com/63159723/146970112-cf3b2d0f-7ad3-41e1-9cbb-dda9c892e947.png)

Although i can not see the server on the multiplayer list on hexxit itself so am unaware as to what may be wrong. 

I cant tell if this is a hexxit setup issue on my side, or a server setup issue, literally any direction for me to go with this would be amazing!

**Comment by xJon** [comment]
Hi, your server is running! If you want to login to a server running on your computer, use `localhost` in the IP field.

**Comment by lauber1954** [comment]
I tried putting localhost in the ip option in the server.properties file, and also i tried in the ip field in minecraft itself, neither worked. It's like its not making a connection?

**Comment by lauber1954** [comment]
i think you may be a wizard, and it may have worked, just gonna try and get my friend on it, but it's just come up, which is further than i got before!

**Comment by lauber1954** [comment]
So i was able to connect to the server fine using the localhost method, but my friend is unable to, im assuming thats because there's no actual ip to connect to as its solely running from the computer without any access? 
If i change localhost to my ip, it doesn't show up at all :/

**Comment by xJon** [comment]
You should leave the field in `server.properties` empty, and login using `localhost` on your end. For your friend to be able to connect, you'd need to port forward - you can find more information about this online or over our Discord :)
