### ISSUE TITLE
Teleport Stones No Longer Work

### ISSUE THREAD

**Issue by Magicmason1000** [xJon/Hexxit-II#87]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable
- **Version**: 1.2.1

**Describe the issue**
I updated from 1.1.0 to 1.2.1 and suddenly my Teleport Stones (Chocolate Quest Repoured mod) don't work. They still have their coordinates set to the location I previously set them at, but using them does nothing.
![image](https://user-images.githubusercontent.com/46111269/147371175-e81c5fac-3f63-4b80-9492-e5c159b8663a.png)
I've tried holding right click, just pressing right click, and shifting + right clicking. They still have the animation of pulling back and waiting for a release, but releasing doesn't do anything. I also tried creating a new world in creative mode and testing them out, but that still did nothing. However, I have Warp Stones (from Waystone mod) and those still work.

**Comment by xJon** [comment]
Do new Teleport Stones work? Do you have any steps to reproduce this issue?
This should probably be reported over https://github.com/TeamChocoQuest/ChocolateQuestRepoured/issues :)

**Comment by Magicmason1000** [comment]
I just found the problem, and I'm really dumb. The TP Stones must have been updated to auto-release after holding them down for a while. I was charging (click and holding) the stone and manually releasing like how it used to work, but that wasn't working because I just had to keep holding down and they worked on their own. Sorry for wasting your time :|

**Comment by xJon** [comment]
No worries, that does sound confusing! I'm glad you reached out for help nonetheless :)
