### ISSUE TITLE
[Suggestion] Allow 'Recall' enchantment on weapons

### ISSUE THREAD

**Issue by yfunk** [xJon/Hexxit-II#89]
## What

The [Capsule](https://www.curseforge.com/minecraft/mc-mods/capsule) mod, which was recently added to the modpack, introduces the [Recall enchantment](https://github.com/Lythom/capsule/wiki#recall).

> Effect: whenever a recall enchanted item is dropped and touches the ground, it comes back into the thrower inventory after a last update. When in contact of water or lava the recall is immediate (prevent burning).

In the default configuration only capsule items can get the enchantment using the enchanting table, although it would be very useful to allow this enchantment on other items like weapons.

## Why

Currently there isn't really a way to counter special mob variants that drop the item a player is holding in their hand. Fighting them can often get really hard (if not near impossible) and annoying when the players constantly losses their weapon. 

Allowing this enchantment on weapons would add a way to make fighting these kinds of monsters less painful.

## How

Update mod configuration in `config/capsule.cfg`

```
# Possible targets for the enchantment. By default : null.
# Possible values are ALL, ARMOR, ARMOR_FEET, ARMOR_LEGS, ARMOR_TORSO, ARMOR_HEAD, WEAPON, DIGGER, FISHING_ROD, BREAKABLE, BOW, null.
# If null or empty, Capsules will be the only items to be able to get this Enchantment.
S:recallEnchantType=null
```
I think it would be fine to make this `EnumEnchantmentType.ALL`, so both weapons and tools can get the enchantment. I also tested using `EnumEnchantmentType.WEAPON` and it doesn't break the enchantment for capsule items.

**Comment by xJon** [comment]
This was added in version `1.3.0`! Thank you for the suggestion :)

**Comment by BulletPR00FXX** [comment]
this doesn't seem to work for me when used on tinkers weapons, is this intended?

would like to use this enchant on unbreakable weapons on pedestals so that they do not need frequent replacement.   Thanks!

**Comment by xJon** [comment]
@BulletPR00FXX This is intended as Tinkers gear is not supposed to normally be enchanted! You could disable this Infernal Mobs ability in the config file, or use a high durability non-Tinkers sword (Diamond Giant Sword?) with Unbreaking III and Mending.

**Comment by xJon** [comment]
For reference, this idea was great in theory but didn't work in practice - thankfully thanks to @ACGaming's https://github.com/ACGaming/UniversalTweaks/commit/12c94746d505dcb340439ac2ced6c642352579ce this feature will work as intended in Hexxit II v1.5.0+.

**Comment by xJon** [comment]
Works perfectly in `1.5.0`.
