### ISSUE TITLE
server doesn't work

### ISSUE THREAD

**Issue by loreafin** [xJon/Hexxit-II#90]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**

What I am doing wrong?
![image](https://user-images.githubusercontent.com/96753141/147514304-868d809b-464a-412c-8c3d-78a396f7dee2.png)

**Comment by xJon** [comment]
Did you resolve the issue?
