### ISSUE TITLE
playerdata rollback on save & exit

### ISSUE THREAD

**Issue by Keith-UCT** [xJon/Hexxit-II#91]
Basic: 
When saving and exiting, playerdata doesn't seem to be overwritten with the new info, resulting in an inventory rollback when starting a new session in the save. This does not happen all the time, but is especially noticeable after long sessions or extensive progress.

Issue:
Major loss of progress after long sessions of playing, loss of inventory, duplication of items (stored items re-appearing in inventory and still persisting in chests)

**Comment by xJon** [comment]
Do you have any steps to reproduce this issue, or does it occur just on random after long playing sessions? This is the first time I'm hearing of it, odd

**Comment by Keith-UCT** [comment]
So far, no noticable reproduction steps. Thought it might have been a UUID error (re-opening technic or minecraft launcher while in game), but I only found one UUID file set in the playerdata folder.

**Comment by xJon** [comment]
Did you try rolling back to a recent world backup?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
