### ISSUE TITLE
Server Issues

### ISSUE THREAD

**Issue by BulletPR00FXX** [xJon/Hexxit-II#92]
2 separate issues here. Im running a private server on Apex Hosting.  Have had a few people look at it (from apex hosting) who werent sure what the issues are. Im hopeful that you can point me in a good direction!

problem 1: I have tried editing a few config files. after restarting the server, the changes do not seem to have worked. Some are not able to be easily tested, such as drop rates and spawn rates. this is everything that I have changed:

I edited the following config files:
bountiful - tested, not working
# Whether or not the bounty board can be broken (Default: true).
B:"Board Breakable?"=true

# Whether or not bounty boards will drop when broken (Default: true).
B:"Board Drops on Break"=true

culinaryconstruct - tested - seemed to work
# The maximum amount of food that a single sandwich can give
I:"Max Food Per Sandwich"=20

dimdoors - tested - not working
B:closeDoorBehind=false

hexxitgear - hard to test
# The 1/n chance for a hexbiscus to generate. Lower numbers means more. [range: 1 ~ 600, default: 50]
I:"Hexbiscus Chance"=40
}

tinkersaddons - tested - not working
Re-adds the diamond + gold block recipe to increase modifiers on a tool if enabled

B:"Enable 1st bonus modifier mod for tools"=true

# Re-adds the diamond block + gold apple recipe to increase modifiers on a tool if enabled
B:"Enable 2nd bonus modifier mod for tools"=true

# Re-adds the nether star recipe to increase modifiers on a tool if enabled
B:"Enable 3rd bonus modifier mod for tools"=true

TinkerToolLeveling - tested - not working (finally has started to work, not sure what changed this)
# Maximum achievable levels. If set to 0 or lower there is no upper limit
maximumLevels=0

tombmanygraves - tested - working
# If set to true, graves will be able to be accessed/manipulated by any player - not just the one who owns the grave. (Defaults to false.)
B:allowGraveRobbing=true

tumbleweed - untested
# Should tumbleweeds damage crops.
B:"Damage Crops"=false

Waystones - tested - not working
The amount of xp levels to use for dimensional warp.

I:"Dimensional Warp XP Cost"=0

# Set to false to make all global waystones not cost any experience, regardless of method used.
B:"Global Waystones Cost XP"=false

# The maximum xp cost when Blocks per XP Level is enabled.
# Min: 1
# Max: 2147483647
I:"Maximum XP Cost"=0

# If enabled, the warp stone costs experience when used, based on the distance travelled.
B:"Warp Stone Costs XP"=false

# If enabled, waystones cost experience when used, based on the distance travelled.
B:"Waystone Costs XP"=false

Problem 2: I added Spongeforge. It crashed my server. I cannot seem to get it to work. any advice is appreciated.
I read that foamfix could have been an issue. i changed the following config to see if it helps. it does not seem to help.

foamfix
# Optimizes BlockPos mutable/immutable getters to run on the same variables, letting them be inlined and thus theoretically increasing performance. [default: true]
B:optimizedBlockPos=false

# Fix a bug in chunk serialization leading to crashes. Originally found and fixed by Aaron1011 of Sponge. [default: true]
B:patchChunkSerialization=false

Thanks in advance for any help you can give!

**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  spongeforge, it causes a crash
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**

A clear description of what help is needed.

**Comment by BulletPR00FXX** [comment]
Here is the reply from my support ticket on Apex Hosting:

Hello Brent,

I have been experimenting with Sponge for a while but I have not been able to get it running on your server. The documentation for it says that it is incompatible with FoamFix and Phosphor. I removed both from the server and made some other recommended adjustments, but it completely refuses to start.

At this point I would recommend either removing sponge altogether, trying a completely fresh install of the pack, or contacting the sponge developers on their discord server as there may be incompatibilities that are not in the official documentation.

If you want to try a fresh install of the pack, go to FTP File Access and delete the mods, jar, and config folders. The server will do the rest of the work for you after a restart.

Davy Davison
Support Operator
Apex Hosting

**Comment by BulletPR00FXX** [comment]
One of the other members at Apex suggested I either contact you, or spongeforge.  I am hopeful to get some info for plugin support here!

**Comment by xJon** [comment]
Regarding the configs, Bountiful might need to have the changes applied both on the server and the client.
Regarding SpongeForge, you might need to manually downgrade the Forge version shipped with the modpack to match Sponge's, although it is not recommended for security reasons. If you still want to do it you should follow Mojang's instructions for MC 1.12-1.16.5 found over https://www.minecraft.net/en-us/article/important-message--security-vulnerability-java-edition

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
