### ISSUE TITLE
Hexxit II Server can't get past "logging in" screen 

### ISSUE THREAD

**Issue by Karlion24** [xJon/Hexxit-II#94]
Hi 

I am running the Hexxit II mod on the technic launcher to connect to a Minecraft server and play with my friends. 

I played fine one day and then the next time I tried to log in I got stuck at the logging in screen for the server connection. 

I've managed to connect since the migration, I've tried logging out of all Microsoft devices and then logging back onto Hexxit II. I've tried reinstalling both Minecraft and Hexxit II. I've checked the launder consolse and there is no error log that appears simply says I am connecting and goes no further before saying "connection lost" 

Any ideas on how to resolve this please?

- **Are you using Java 8, 64-bit?**: / yes

**Comment by xJon** [comment]
Hi! Can you connect to other servers?

**Comment by Karlion24** [comment]
Hi! I haven't tried any other servers yet Jon, do you have an IP address I can try? I looked online but couldn't find any. Been trying for three evenings to fix this now so if you can sort it you'll be a legend!

**Comment by xJon** [comment]
You can find servers over Technic's Discord - https://discord.com/invite/technic

**Comment by Karlion24** [comment]
Dunno if I'm dense but finding it difficult to locate a server IP address when checking through all those groups, did you have one I could try? my friends actually migrated the server to a new IP and neither of them worked so I think I have tried more then one anyway

**Comment by Karlion24** [comment]
Okay I was being dense, managed it (assumed I needed numbers). It worked fine it just seems to be this world that I'm trying to join, but can connect to other Hexxit II servers fine

**Comment by xJon** [comment]
And can your friends login to the server you are unable to? In this case I'd need to see the server log, although updating to the recently released version `1.3.0` might also be helpful!

**Comment by Karlion24** [comment]
I managed to fix the issue. the problem was my character file on the server was corrupted. Deleted this and I could then log in

**Comment by xJon** [comment]
Glad you managed to fix it!
