### ISSUE TITLE
two mods don't work 

### ISSUE THREAD

**Issue by Lisax37** [xJon/Hexxit-II#96]
I downloaded hexxit 2 from the tecnec launcher. It installed perfectly, but when i opened minecraft hexxit, all the mods were loading and there was a problem with the chocolate quest repoured mod and the bountiful mod, it both crashed and i couldn't open hexxit and play it. i really want to play this, can you help me out?
Thnkyou in advance.

**Comment by xJon** [comment]
This sounds like https://github.com/xJon/Hexxit-II/issues/77 - if you're playing on a Mac, make sure to use version `1.1.0` of the modpack. Soon a new version with a fix for this will be released!

**Comment by xJon** [comment]
This is fixed using the latest version of Hexxit II.
