### ISSUE TITLE
Issues when changing dimensions

### ISSUE THREAD

**Issue by GarbageLumi** [xJon/Hexxit-II#97]
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

When walking through a dimensional door it says that there was an error in trying to teleport me. There is no way to fix it. I've tried spawning in my own doors, going through naturally made ones. All of them give the same message and put me into a black void. I then have to reload the game where it will then drop me out the world, kill me, and take me to limbo.

**Comment by EliasWorthing** [comment]
Same thing happens to me. Here is my log file in case it helps someone.
[latest.log](https://github.com/xJon/Hexxit-II/files/7879374/latest.log)

**Comment by xJon** [comment]
Only naturally generated doors should work, from my understanding, but it is troublesome if they give you errors.
Did you test naturally spawning doors in other worlds?

**Comment by xJon** [comment]
I can reproduce this, thank you for the report. Will look into the issue!

**Comment by xJon** [comment]
@EliasWorthing Can you reproduce this issue after replacing the installed Chocolate Quest Repoured mod version with [this one](https://www.curseforge.com/minecraft/mc-mods/cqrepoured/files/3605767)?

**Comment by xJon** [comment]
Should be fixed using the latest version of the modpack (`1.3.1`)!
